WARNING: Error loading config file: /home/.docker/config.json: Invalid auth configuration file
-- Logs begin at Tue 2021-08-17 17:50:16 UTC, end at Tue 2021-08-17 17:51:29 UTC. --
Aug 17 17:50:16 remote-control-plane systemd[1]: Condition check resulted in kubelet: The Kubernetes Node Agent being skipped.
Aug 17 17:50:21 remote-control-plane systemd[1]: Starting kubelet: The Kubernetes Node Agent...
Aug 17 17:50:21 remote-control-plane systemd[1]: Started kubelet: The Kubernetes Node Agent.
Aug 17 17:50:21 remote-control-plane kubelet[287]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Aug 17 17:50:21 remote-control-plane kubelet[287]: Flag --provider-id has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Aug 17 17:50:21 remote-control-plane kubelet[287]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Aug 17 17:50:21 remote-control-plane kubelet[287]: Flag --cgroup-root has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Aug 17 17:50:21 remote-control-plane kubelet[287]: I0817 17:50:21.466588     287 server.go:197] "Warning: For remote container runtime, --pod-infra-container-image is ignored in kubelet, which should be set in that remote runtime instead"
Aug 17 17:50:21 remote-control-plane kubelet[287]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Aug 17 17:50:21 remote-control-plane kubelet[287]: Flag --provider-id has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Aug 17 17:50:21 remote-control-plane kubelet[287]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Aug 17 17:50:21 remote-control-plane kubelet[287]: Flag --cgroup-root has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Aug 17 17:50:21 remote-control-plane kubelet[287]: I0817 17:50:21.714239     287 server.go:440] "Kubelet version" kubeletVersion="v1.21.1"
Aug 17 17:50:21 remote-control-plane kubelet[287]: I0817 17:50:21.714578     287 server.go:851] "Client rotation is on, will bootstrap in background"
Aug 17 17:50:21 remote-control-plane kubelet[287]: I0817 17:50:21.719903     287 dynamic_cafile_content.go:167] Starting client-ca-bundle::/etc/kubernetes/pki/ca.crt
Aug 17 17:50:21 remote-control-plane kubelet[287]: E0817 17:50:21.728716     287 certificate_manager.go:437] Failed while requesting a signed certificate from the master: cannot create certificate signing request: Post "https://remote-control-plane:6443/apis/certificates.k8s.io/v1/certificatesigningrequests": dial tcp 172.18.0.2:6443: connect: connection refused
Aug 17 17:50:23 remote-control-plane kubelet[287]: E0817 17:50:23.810789     287 certificate_manager.go:437] Failed while requesting a signed certificate from the master: cannot create certificate signing request: Post "https://remote-control-plane:6443/apis/certificates.k8s.io/v1/certificatesigningrequests": dial tcp 172.18.0.2:6443: connect: connection refused
Aug 17 17:50:26 remote-control-plane kubelet[287]: W0817 17:50:26.729516     287 sysinfo.go:203] Nodes topology is not available, providing CPU topology
Aug 17 17:50:26 remote-control-plane kubelet[287]: I0817 17:50:26.740287     287 container_manager_linux.go:278] "Container manager verified user specified cgroup-root exists" cgroupRoot=[kubelet]
Aug 17 17:50:26 remote-control-plane kubelet[287]: I0817 17:50:26.740356     287 container_manager_linux.go:283] "Creating Container Manager object based on Node Config" nodeConfig={RuntimeCgroupsName: SystemCgroupsName: KubeletCgroupsName: ContainerRuntime:remote CgroupsPerQOS:true CgroupRoot:/kubelet CgroupDriver:cgroupfs KubeletRootDir:/var/lib/kubelet ProtectKernelDefaults:false NodeAllocatableConfig:{KubeReservedCgroupName: SystemReservedCgroupName: ReservedSystemCPUs: EnforceNodeAllocatable:map[pods:{}] KubeReserved:map[] SystemReserved:map[] HardEvictionThresholds:[]} QOSReserved:map[] ExperimentalCPUManagerPolicy:none ExperimentalTopologyManagerScope:container ExperimentalCPUManagerReconcilePeriod:10s ExperimentalMemoryManagerPolicy:None ExperimentalMemoryManagerReservedMemory:[] ExperimentalPodPidsLimit:-1 EnforceCPULimits:true CPUCFSQuotaPeriod:100ms ExperimentalTopologyManagerPolicy:none}
Aug 17 17:50:26 remote-control-plane kubelet[287]: I0817 17:50:26.741533     287 topology_manager.go:120] "Creating topology manager with policy per scope" topologyPolicyName="none" topologyScopeName="container"
Aug 17 17:50:26 remote-control-plane kubelet[287]: I0817 17:50:26.741578     287 container_manager_linux.go:314] "Initializing Topology Manager" policy="none" scope="container"
Aug 17 17:50:26 remote-control-plane kubelet[287]: I0817 17:50:26.741600     287 container_manager_linux.go:319] "Creating device plugin manager" devicePluginEnabled=true
Aug 17 17:50:26 remote-control-plane kubelet[287]: I0817 17:50:26.741751     287 remote_runtime.go:62] parsed scheme: ""
Aug 17 17:50:26 remote-control-plane kubelet[287]: I0817 17:50:26.741774     287 remote_runtime.go:62] scheme "" not registered, fallback to default scheme
Aug 17 17:50:26 remote-control-plane kubelet[287]: I0817 17:50:26.741816     287 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{/run/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}
Aug 17 17:50:26 remote-control-plane kubelet[287]: I0817 17:50:26.741834     287 clientconn.go:948] ClientConn switching balancer to "pick_first"
Aug 17 17:50:26 remote-control-plane kubelet[287]: I0817 17:50:26.741914     287 remote_image.go:50] parsed scheme: ""
Aug 17 17:50:26 remote-control-plane kubelet[287]: I0817 17:50:26.741930     287 remote_image.go:50] scheme "" not registered, fallback to default scheme
Aug 17 17:50:26 remote-control-plane kubelet[287]: I0817 17:50:26.741949     287 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{/run/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}
Aug 17 17:50:26 remote-control-plane kubelet[287]: I0817 17:50:26.741965     287 clientconn.go:948] ClientConn switching balancer to "pick_first"
Aug 17 17:50:26 remote-control-plane kubelet[287]: I0817 17:50:26.742029     287 kubelet.go:404] "Attempting to sync node with API server"
Aug 17 17:50:26 remote-control-plane kubelet[287]: I0817 17:50:26.742088     287 kubelet.go:272] "Adding static pod path" path="/etc/kubernetes/manifests"
Aug 17 17:50:26 remote-control-plane kubelet[287]: I0817 17:50:26.742128     287 kubelet.go:283] "Adding apiserver pod source"
Aug 17 17:50:26 remote-control-plane kubelet[287]: I0817 17:50:26.742150     287 apiserver.go:42] "Waiting for node sync before watching apiserver pods"
Aug 17 17:50:26 remote-control-plane kubelet[287]: I0817 17:50:26.743592     287 kuberuntime_manager.go:222] "Container runtime initialized" containerRuntime="containerd" version="v1.5.1" apiVersion="v1alpha2"
Aug 17 17:50:26 remote-control-plane kubelet[287]: E0817 17:50:26.744657     287 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Node: failed to list *v1.Node: Get "https://remote-control-plane:6443/api/v1/nodes?fieldSelector=metadata.name%3Dremote-control-plane&limit=500&resourceVersion=0": dial tcp 172.18.0.2:6443: connect: connection refused
Aug 17 17:50:26 remote-control-plane kubelet[287]: E0817 17:50:26.744747     287 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Service: failed to list *v1.Service: Get "https://remote-control-plane:6443/api/v1/services?limit=500&resourceVersion=0": dial tcp 172.18.0.2:6443: connect: connection refused
Aug 17 17:50:27 remote-control-plane kubelet[287]: E0817 17:50:27.668627     287 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Service: failed to list *v1.Service: Get "https://remote-control-plane:6443/api/v1/services?limit=500&resourceVersion=0": dial tcp 172.18.0.2:6443: connect: connection refused
Aug 17 17:50:27 remote-control-plane kubelet[287]: E0817 17:50:27.780477     287 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Node: failed to list *v1.Node: Get "https://remote-control-plane:6443/api/v1/nodes?fieldSelector=metadata.name%3Dremote-control-plane&limit=500&resourceVersion=0": dial tcp 172.18.0.2:6443: connect: connection refused
Aug 17 17:50:27 remote-control-plane kubelet[287]: E0817 17:50:27.941702     287 certificate_manager.go:437] Failed while requesting a signed certificate from the master: cannot create certificate signing request: Post "https://remote-control-plane:6443/apis/certificates.k8s.io/v1/certificatesigningrequests": dial tcp 172.18.0.2:6443: connect: connection refused
Aug 17 17:50:29 remote-control-plane kubelet[287]: E0817 17:50:29.976392     287 aws_credentials.go:77] while getting AWS credentials NoCredentialProviders: no valid providers in chain. Deprecated.
Aug 17 17:50:29 remote-control-plane kubelet[287]:         For verbose messaging see aws.Config.CredentialsChainVerboseErrors
Aug 17 17:50:29 remote-control-plane kubelet[287]: W0817 17:50:29.976775     287 probe.go:268] Flexvolume plugin directory at /usr/libexec/kubernetes/kubelet-plugins/volume/exec/ does not exist. Recreating.
Aug 17 17:50:29 remote-control-plane kubelet[287]: I0817 17:50:29.977386     287 server.go:1190] "Started kubelet"
Aug 17 17:50:29 remote-control-plane kubelet[287]: I0817 17:50:29.977615     287 server.go:149] "Starting to listen" address="0.0.0.0" port=10250
Aug 17 17:50:29 remote-control-plane kubelet[287]: E0817 17:50:29.978453     287 event.go:273] Unable to write event: '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"remote-control-plane.169c295997d3b608", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"remote-control-plane", UID:"remote-control-plane", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"Starting", Message:"Starting kubelet.", Source:v1.EventSource{Component:"kubelet", Host:"remote-control-plane"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xc03f1b997a410408, ext:8650794501, loc:(*time.Location)(0x74aba00)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xc03f1b997a410408, ext:8650794501, loc:(*time.Location)(0x74aba00)}}, Count:1, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'Post "https://remote-control-plane:6443/api/v1/namespaces/default/events": dial tcp 172.18.0.2:6443: connect: connection refused'(may retry after sleeping)
Aug 17 17:50:29 remote-control-plane kubelet[287]: I0817 17:50:29.979032     287 server.go:405] "Adding debug handlers to kubelet server"
Aug 17 17:50:29 remote-control-plane kubelet[287]: I0817 17:50:29.982220     287 fs_resource_analyzer.go:67] "Starting FS ResourceAnalyzer"
Aug 17 17:50:29 remote-control-plane kubelet[287]: I0817 17:50:29.983124     287 volume_manager.go:271] "Starting Kubelet Volume Manager"
Aug 17 17:50:29 remote-control-plane kubelet[287]: I0817 17:50:29.983279     287 desired_state_of_world_populator.go:141] "Desired state populator starts to run"
Aug 17 17:50:29 remote-control-plane kubelet[287]: E0817 17:50:29.984968     287 controller.go:144] failed to ensure lease exists, will retry in 200ms, error: Get "https://remote-control-plane:6443/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/remote-control-plane?timeout=10s": dial tcp 172.18.0.2:6443: connect: connection refused
Aug 17 17:50:29 remote-control-plane kubelet[287]: E0817 17:50:29.985037     287 kubelet.go:2211] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized"
Aug 17 17:50:29 remote-control-plane kubelet[287]: E0817 17:50:29.985219     287 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.CSIDriver: failed to list *v1.CSIDriver: Get "https://remote-control-plane:6443/apis/storage.k8s.io/v1/csidrivers?limit=500&resourceVersion=0": dial tcp 172.18.0.2:6443: connect: connection refused
Aug 17 17:50:29 remote-control-plane kubelet[287]: I0817 17:50:29.985602     287 client.go:86] parsed scheme: "unix"
Aug 17 17:50:29 remote-control-plane kubelet[287]: I0817 17:50:29.985643     287 client.go:86] scheme "unix" not registered, fallback to default scheme
Aug 17 17:50:29 remote-control-plane kubelet[287]: I0817 17:50:29.985693     287 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}
Aug 17 17:50:29 remote-control-plane kubelet[287]: I0817 17:50:29.985726     287 clientconn.go:948] ClientConn switching balancer to "pick_first"
Aug 17 17:50:29 remote-control-plane kubelet[287]: E0817 17:50:29.986926     287 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Service: failed to list *v1.Service: Get "https://remote-control-plane:6443/api/v1/services?limit=500&resourceVersion=0": dial tcp 172.18.0.2:6443: connect: connection refused
Aug 17 17:50:30 remote-control-plane kubelet[287]: I0817 17:50:30.026175     287 cpu_manager.go:199] "Starting CPU manager" policy="none"
Aug 17 17:50:30 remote-control-plane kubelet[287]: I0817 17:50:30.026239     287 cpu_manager.go:200] "Reconciling" reconcilePeriod="10s"
Aug 17 17:50:30 remote-control-plane kubelet[287]: I0817 17:50:30.026323     287 state_mem.go:36] "Initialized new in-memory state store"
Aug 17 17:50:30 remote-control-plane kubelet[287]: I0817 17:50:30.028000     287 policy_none.go:44] "None policy: Start"
Aug 17 17:50:30 remote-control-plane kubelet[287]: I0817 17:50:30.035703     287 manager.go:600] "Failed to retrieve checkpoint" checkpoint="kubelet_internal_checkpoint" err="checkpoint is not found"
Aug 17 17:50:30 remote-control-plane kubelet[287]: I0817 17:50:30.035941     287 plugin_manager.go:114] "Starting Kubelet Plugin Manager"
Aug 17 17:50:30 remote-control-plane kubelet[287]: E0817 17:50:30.036789     287 eviction_manager.go:255] "Eviction manager: failed to get summary stats" err="failed to get node info: node \"remote-control-plane\" not found"
Aug 17 17:50:30 remote-control-plane kubelet[287]: E0817 17:50:30.083482     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:30 remote-control-plane kubelet[287]: I0817 17:50:30.085672     287 kubelet_node_status.go:71] "Attempting to register node" node="remote-control-plane"
Aug 17 17:50:30 remote-control-plane kubelet[287]: E0817 17:50:30.086523     287 kubelet_node_status.go:93] "Unable to register node with API server" err="Post \"https://remote-control-plane:6443/api/v1/nodes\": dial tcp 172.18.0.2:6443: connect: connection refused" node="remote-control-plane"
Aug 17 17:50:30 remote-control-plane kubelet[287]: E0817 17:50:30.183772     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:30 remote-control-plane kubelet[287]: E0817 17:50:30.186578     287 controller.go:144] failed to ensure lease exists, will retry in 400ms, error: Get "https://remote-control-plane:6443/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/remote-control-plane?timeout=10s": dial tcp 172.18.0.2:6443: connect: connection refused
Aug 17 17:50:30 remote-control-plane kubelet[287]: E0817 17:50:30.283860     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:30 remote-control-plane kubelet[287]: I0817 17:50:30.288907     287 kubelet_node_status.go:71] "Attempting to register node" node="remote-control-plane"
Aug 17 17:50:30 remote-control-plane kubelet[287]: E0817 17:50:30.290304     287 kubelet_node_status.go:93] "Unable to register node with API server" err="Post \"https://remote-control-plane:6443/api/v1/nodes\": dial tcp 172.18.0.2:6443: connect: connection refused" node="remote-control-plane"
Aug 17 17:50:30 remote-control-plane kubelet[287]: I0817 17:50:30.308594     287 kubelet_network_linux.go:56] "Initialized protocol iptables rules." protocol=IPv4
Aug 17 17:50:30 remote-control-plane kubelet[287]: E0817 17:50:30.384398     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:30 remote-control-plane kubelet[287]: I0817 17:50:30.453428     287 kubelet_network_linux.go:56] "Initialized protocol iptables rules." protocol=IPv6
Aug 17 17:50:30 remote-control-plane kubelet[287]: I0817 17:50:30.453491     287 status_manager.go:157] "Starting to sync pod status with apiserver"
Aug 17 17:50:30 remote-control-plane kubelet[287]: I0817 17:50:30.453523     287 kubelet.go:1846] "Starting kubelet main sync loop"
Aug 17 17:50:30 remote-control-plane kubelet[287]: E0817 17:50:30.453591     287 kubelet.go:1870] "Skipping pod synchronization" err="PLEG is not healthy: pleg has yet to be successful"
Aug 17 17:50:30 remote-control-plane kubelet[287]: E0817 17:50:30.455012     287 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.RuntimeClass: failed to list *v1.RuntimeClass: Get "https://remote-control-plane:6443/apis/node.k8s.io/v1/runtimeclasses?limit=500&resourceVersion=0": dial tcp 172.18.0.2:6443: connect: connection refused
Aug 17 17:50:30 remote-control-plane kubelet[287]: E0817 17:50:30.484967     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:30 remote-control-plane kubelet[287]: I0817 17:50:30.554971     287 topology_manager.go:187] "Topology Admit Handler"
Aug 17 17:50:30 remote-control-plane kubelet[287]: I0817 17:50:30.556267     287 topology_manager.go:187] "Topology Admit Handler"
Aug 17 17:50:30 remote-control-plane kubelet[287]: I0817 17:50:30.557319     287 topology_manager.go:187] "Topology Admit Handler"
Aug 17 17:50:30 remote-control-plane kubelet[287]: I0817 17:50:30.559002     287 status_manager.go:566] "Failed to get status for pod" podUID=91fcc6c180befeefc8bb69fd100aff4d pod="kube-system/kube-scheduler-remote-control-plane" error="Get \"https://remote-control-plane:6443/api/v1/namespaces/kube-system/pods/kube-scheduler-remote-control-plane\": dial tcp 172.18.0.2:6443: connect: connection refused"
Aug 17 17:50:30 remote-control-plane kubelet[287]: I0817 17:50:30.559079     287 topology_manager.go:187] "Topology Admit Handler"
Aug 17 17:50:30 remote-control-plane kubelet[287]: I0817 17:50:30.560268     287 status_manager.go:566] "Failed to get status for pod" podUID=464f70cc19489045f3a12d8fc40c8986 pod="kube-system/etcd-remote-control-plane" error="Get \"https://remote-control-plane:6443/api/v1/namespaces/kube-system/pods/etcd-remote-control-plane\": dial tcp 172.18.0.2:6443: connect: connection refused"
Aug 17 17:50:30 remote-control-plane kubelet[287]: I0817 17:50:30.560804     287 status_manager.go:566] "Failed to get status for pod" podUID=9b0a6fe1ae446c8289ca29f8bcbb3394 pod="kube-system/kube-apiserver-remote-control-plane" error="Get \"https://remote-control-plane:6443/api/v1/namespaces/kube-system/pods/kube-apiserver-remote-control-plane\": dial tcp 172.18.0.2:6443: connect: connection refused"
Aug 17 17:50:30 remote-control-plane kubelet[287]: I0817 17:50:30.563032     287 status_manager.go:566] "Failed to get status for pod" podUID=00413c9191df709893361d18bc0fcc16 pod="kube-system/kube-controller-manager-remote-control-plane" error="Get \"https://remote-control-plane:6443/api/v1/namespaces/kube-system/pods/kube-controller-manager-remote-control-plane\": dial tcp 172.18.0.2:6443: connect: connection refused"
Aug 17 17:50:30 remote-control-plane kubelet[287]: E0817 17:50:30.575760     287 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Node: failed to list *v1.Node: Get "https://remote-control-plane:6443/api/v1/nodes?fieldSelector=metadata.name%3Dremote-control-plane&limit=500&resourceVersion=0": dial tcp 172.18.0.2:6443: connect: connection refused
Aug 17 17:50:30 remote-control-plane kubelet[287]: E0817 17:50:30.585308     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:30 remote-control-plane kubelet[287]: I0817 17:50:30.585335     287 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"ca-certs\" (UniqueName: \"kubernetes.io/host-path/9b0a6fe1ae446c8289ca29f8bcbb3394-ca-certs\") pod \"kube-apiserver-remote-control-plane\" (UID: \"9b0a6fe1ae446c8289ca29f8bcbb3394\") "
Aug 17 17:50:30 remote-control-plane kubelet[287]: I0817 17:50:30.585760     287 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"etc-ca-certificates\" (UniqueName: \"kubernetes.io/host-path/9b0a6fe1ae446c8289ca29f8bcbb3394-etc-ca-certificates\") pod \"kube-apiserver-remote-control-plane\" (UID: \"9b0a6fe1ae446c8289ca29f8bcbb3394\") "
Aug 17 17:50:30 remote-control-plane kubelet[287]: I0817 17:50:30.585979     287 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"k8s-certs\" (UniqueName: \"kubernetes.io/host-path/9b0a6fe1ae446c8289ca29f8bcbb3394-k8s-certs\") pod \"kube-apiserver-remote-control-plane\" (UID: \"9b0a6fe1ae446c8289ca29f8bcbb3394\") "
Aug 17 17:50:30 remote-control-plane kubelet[287]: I0817 17:50:30.586189     287 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"flexvolume-dir\" (UniqueName: \"kubernetes.io/host-path/00413c9191df709893361d18bc0fcc16-flexvolume-dir\") pod \"kube-controller-manager-remote-control-plane\" (UID: \"00413c9191df709893361d18bc0fcc16\") "
Aug 17 17:50:30 remote-control-plane kubelet[287]: I0817 17:50:30.586355     287 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"kubeconfig\" (UniqueName: \"kubernetes.io/host-path/00413c9191df709893361d18bc0fcc16-kubeconfig\") pod \"kube-controller-manager-remote-control-plane\" (UID: \"00413c9191df709893361d18bc0fcc16\") "
Aug 17 17:50:30 remote-control-plane kubelet[287]: I0817 17:50:30.586510     287 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"usr-local-share-ca-certificates\" (UniqueName: \"kubernetes.io/host-path/00413c9191df709893361d18bc0fcc16-usr-local-share-ca-certificates\") pod \"kube-controller-manager-remote-control-plane\" (UID: \"00413c9191df709893361d18bc0fcc16\") "
Aug 17 17:50:30 remote-control-plane kubelet[287]: I0817 17:50:30.586662     287 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"usr-share-ca-certificates\" (UniqueName: \"kubernetes.io/host-path/9b0a6fe1ae446c8289ca29f8bcbb3394-usr-share-ca-certificates\") pod \"kube-apiserver-remote-control-plane\" (UID: \"9b0a6fe1ae446c8289ca29f8bcbb3394\") "
Aug 17 17:50:30 remote-control-plane kubelet[287]: I0817 17:50:30.586869     287 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"usr-share-ca-certificates\" (UniqueName: \"kubernetes.io/host-path/00413c9191df709893361d18bc0fcc16-usr-share-ca-certificates\") pod \"kube-controller-manager-remote-control-plane\" (UID: \"00413c9191df709893361d18bc0fcc16\") "
Aug 17 17:50:30 remote-control-plane kubelet[287]: I0817 17:50:30.586935     287 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"kubeconfig\" (UniqueName: \"kubernetes.io/host-path/91fcc6c180befeefc8bb69fd100aff4d-kubeconfig\") pod \"kube-scheduler-remote-control-plane\" (UID: \"91fcc6c180befeefc8bb69fd100aff4d\") "
Aug 17 17:50:30 remote-control-plane kubelet[287]: I0817 17:50:30.586995     287 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"etcd-certs\" (UniqueName: \"kubernetes.io/host-path/464f70cc19489045f3a12d8fc40c8986-etcd-certs\") pod \"etcd-remote-control-plane\" (UID: \"464f70cc19489045f3a12d8fc40c8986\") "
Aug 17 17:50:30 remote-control-plane kubelet[287]: I0817 17:50:30.587092     287 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"etcd-data\" (UniqueName: \"kubernetes.io/host-path/464f70cc19489045f3a12d8fc40c8986-etcd-data\") pod \"etcd-remote-control-plane\" (UID: \"464f70cc19489045f3a12d8fc40c8986\") "
Aug 17 17:50:30 remote-control-plane kubelet[287]: I0817 17:50:30.587138     287 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"usr-local-share-ca-certificates\" (UniqueName: \"kubernetes.io/host-path/9b0a6fe1ae446c8289ca29f8bcbb3394-usr-local-share-ca-certificates\") pod \"kube-apiserver-remote-control-plane\" (UID: \"9b0a6fe1ae446c8289ca29f8bcbb3394\") "
Aug 17 17:50:30 remote-control-plane kubelet[287]: I0817 17:50:30.587174     287 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"ca-certs\" (UniqueName: \"kubernetes.io/host-path/00413c9191df709893361d18bc0fcc16-ca-certs\") pod \"kube-controller-manager-remote-control-plane\" (UID: \"00413c9191df709893361d18bc0fcc16\") "
Aug 17 17:50:30 remote-control-plane kubelet[287]: I0817 17:50:30.587215     287 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"etc-ca-certificates\" (UniqueName: \"kubernetes.io/host-path/00413c9191df709893361d18bc0fcc16-etc-ca-certificates\") pod \"kube-controller-manager-remote-control-plane\" (UID: \"00413c9191df709893361d18bc0fcc16\") "
Aug 17 17:50:30 remote-control-plane kubelet[287]: I0817 17:50:30.587251     287 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"k8s-certs\" (UniqueName: \"kubernetes.io/host-path/00413c9191df709893361d18bc0fcc16-k8s-certs\") pod \"kube-controller-manager-remote-control-plane\" (UID: \"00413c9191df709893361d18bc0fcc16\") "
Aug 17 17:50:30 remote-control-plane kubelet[287]: E0817 17:50:30.588270     287 controller.go:144] failed to ensure lease exists, will retry in 800ms, error: Get "https://remote-control-plane:6443/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/remote-control-plane?timeout=10s": dial tcp 172.18.0.2:6443: connect: connection refused
Aug 17 17:50:30 remote-control-plane kubelet[287]: E0817 17:50:30.686282     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:30 remote-control-plane kubelet[287]: I0817 17:50:30.691953     287 kubelet_node_status.go:71] "Attempting to register node" node="remote-control-plane"
Aug 17 17:50:30 remote-control-plane kubelet[287]: E0817 17:50:30.692780     287 kubelet_node_status.go:93] "Unable to register node with API server" err="Post \"https://remote-control-plane:6443/api/v1/nodes\": dial tcp 172.18.0.2:6443: connect: connection refused" node="remote-control-plane"
Aug 17 17:50:30 remote-control-plane kubelet[287]: E0817 17:50:30.787112     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:30 remote-control-plane kubelet[287]: E0817 17:50:30.888261     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:30 remote-control-plane kubelet[287]: E0817 17:50:30.913562     287 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.CSIDriver: failed to list *v1.CSIDriver: Get "https://remote-control-plane:6443/apis/storage.k8s.io/v1/csidrivers?limit=500&resourceVersion=0": dial tcp 172.18.0.2:6443: connect: connection refused
Aug 17 17:50:30 remote-control-plane kubelet[287]: E0817 17:50:30.988345     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:31 remote-control-plane kubelet[287]: E0817 17:50:31.089005     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:31 remote-control-plane kubelet[287]: E0817 17:50:31.189928     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:31 remote-control-plane kubelet[287]: E0817 17:50:31.257203     287 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.RuntimeClass: failed to list *v1.RuntimeClass: Get "https://remote-control-plane:6443/apis/node.k8s.io/v1/runtimeclasses?limit=500&resourceVersion=0": dial tcp 172.18.0.2:6443: connect: connection refused
Aug 17 17:50:31 remote-control-plane kubelet[287]: E0817 17:50:31.291123     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:31 remote-control-plane kubelet[287]: E0817 17:50:31.390440     287 controller.go:144] failed to ensure lease exists, will retry in 1.6s, error: Get "https://remote-control-plane:6443/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/remote-control-plane?timeout=10s": dial tcp 172.18.0.2:6443: connect: connection refused
Aug 17 17:50:31 remote-control-plane kubelet[287]: E0817 17:50:31.391931     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:31 remote-control-plane kubelet[287]: E0817 17:50:31.497225     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:31 remote-control-plane kubelet[287]: I0817 17:50:31.501165     287 kubelet_node_status.go:71] "Attempting to register node" node="remote-control-plane"
Aug 17 17:50:31 remote-control-plane kubelet[287]: E0817 17:50:31.502440     287 kubelet_node_status.go:93] "Unable to register node with API server" err="Post \"https://remote-control-plane:6443/api/v1/nodes\": dial tcp 172.18.0.2:6443: connect: connection refused" node="remote-control-plane"
Aug 17 17:50:31 remote-control-plane kubelet[287]: E0817 17:50:31.598638     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:31 remote-control-plane kubelet[287]: E0817 17:50:31.699793     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:31 remote-control-plane kubelet[287]: E0817 17:50:31.801084     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:31 remote-control-plane kubelet[287]: E0817 17:50:31.901246     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:32 remote-control-plane kubelet[287]: E0817 17:50:32.001376     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:32 remote-control-plane kubelet[287]: E0817 17:50:32.110446     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:32 remote-control-plane kubelet[287]: E0817 17:50:32.211255     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:32 remote-control-plane kubelet[287]: E0817 17:50:32.312166     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:32 remote-control-plane kubelet[287]: E0817 17:50:32.413134     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:32 remote-control-plane kubelet[287]: E0817 17:50:32.513262     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:32 remote-control-plane kubelet[287]: E0817 17:50:32.614313     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:32 remote-control-plane kubelet[287]: E0817 17:50:32.716259     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:32 remote-control-plane kubelet[287]: E0817 17:50:32.822222     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:32 remote-control-plane kubelet[287]: E0817 17:50:32.922689     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:33 remote-control-plane kubelet[287]: E0817 17:50:33.024985     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:33 remote-control-plane kubelet[287]: I0817 17:50:33.104863     287 kubelet_node_status.go:71] "Attempting to register node" node="remote-control-plane"
Aug 17 17:50:33 remote-control-plane kubelet[287]: E0817 17:50:33.128183     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:33 remote-control-plane kubelet[287]: E0817 17:50:33.228686     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:33 remote-control-plane kubelet[287]: E0817 17:50:33.329419     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:33 remote-control-plane kubelet[287]: E0817 17:50:33.429637     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:33 remote-control-plane kubelet[287]: E0817 17:50:33.530451     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:33 remote-control-plane kubelet[287]: E0817 17:50:33.631126     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:33 remote-control-plane kubelet[287]: E0817 17:50:33.731540     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:33 remote-control-plane kubelet[287]: E0817 17:50:33.832499     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:33 remote-control-plane kubelet[287]: E0817 17:50:33.934169     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:34 remote-control-plane kubelet[287]: E0817 17:50:34.035081     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:34 remote-control-plane kubelet[287]: E0817 17:50:34.136806     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:34 remote-control-plane kubelet[287]: E0817 17:50:34.238013     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:34 remote-control-plane kubelet[287]: E0817 17:50:34.338672     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:34 remote-control-plane kubelet[287]: E0817 17:50:34.439491     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:34 remote-control-plane kubelet[287]: E0817 17:50:34.540399     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:34 remote-control-plane kubelet[287]: E0817 17:50:34.641121     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:34 remote-control-plane kubelet[287]: E0817 17:50:34.741968     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:34 remote-control-plane kubelet[287]: E0817 17:50:34.843118     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:34 remote-control-plane kubelet[287]: E0817 17:50:34.943481     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:35 remote-control-plane kubelet[287]: E0817 17:50:35.036505     287 kubelet.go:2211] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized"
Aug 17 17:50:35 remote-control-plane kubelet[287]: E0817 17:50:35.043718     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:35 remote-control-plane kubelet[287]: E0817 17:50:35.144232     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:35 remote-control-plane kubelet[287]: E0817 17:50:35.245594     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:35 remote-control-plane kubelet[287]: E0817 17:50:35.346106     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:35 remote-control-plane kubelet[287]: E0817 17:50:35.446908     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:35 remote-control-plane kubelet[287]: E0817 17:50:35.547954     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:35 remote-control-plane kubelet[287]: E0817 17:50:35.648293     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:35 remote-control-plane kubelet[287]: E0817 17:50:35.749026     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:35 remote-control-plane kubelet[287]: E0817 17:50:35.850250     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:35 remote-control-plane kubelet[287]: E0817 17:50:35.951005     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:36 remote-control-plane kubelet[287]: E0817 17:50:36.051572     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:36 remote-control-plane kubelet[287]: E0817 17:50:36.152844     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:36 remote-control-plane kubelet[287]: E0817 17:50:36.253401     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:36 remote-control-plane kubelet[287]: E0817 17:50:36.353881     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:36 remote-control-plane kubelet[287]: E0817 17:50:36.454885     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:36 remote-control-plane kubelet[287]: E0817 17:50:36.555695     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:36 remote-control-plane kubelet[287]: E0817 17:50:36.656946     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:36 remote-control-plane kubelet[287]: E0817 17:50:36.757011     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:36 remote-control-plane kubelet[287]: E0817 17:50:36.857764     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:36 remote-control-plane kubelet[287]: E0817 17:50:36.959003     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:37 remote-control-plane kubelet[287]: E0817 17:50:37.060228     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:37 remote-control-plane kubelet[287]: E0817 17:50:37.161401     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:37 remote-control-plane kubelet[287]: E0817 17:50:37.262620     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:37 remote-control-plane kubelet[287]: E0817 17:50:37.364292     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:37 remote-control-plane kubelet[287]: E0817 17:50:37.465411     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:37 remote-control-plane kubelet[287]: E0817 17:50:37.566661     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:37 remote-control-plane kubelet[287]: E0817 17:50:37.667593     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:37 remote-control-plane kubelet[287]: E0817 17:50:37.768284     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:37 remote-control-plane kubelet[287]: E0817 17:50:37.869128     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:37 remote-control-plane kubelet[287]: E0817 17:50:37.969968     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:38 remote-control-plane kubelet[287]: E0817 17:50:38.071121     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:38 remote-control-plane kubelet[287]: E0817 17:50:38.171957     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:38 remote-control-plane kubelet[287]: E0817 17:50:38.272983     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:38 remote-control-plane kubelet[287]: E0817 17:50:38.373187     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:38 remote-control-plane kubelet[287]: E0817 17:50:38.474008     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:38 remote-control-plane kubelet[287]: E0817 17:50:38.580418     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:38 remote-control-plane kubelet[287]: E0817 17:50:38.681537     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:38 remote-control-plane kubelet[287]: E0817 17:50:38.782146     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:38 remote-control-plane kubelet[287]: E0817 17:50:38.882383     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:38 remote-control-plane kubelet[287]: E0817 17:50:38.982843     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:39 remote-control-plane kubelet[287]: E0817 17:50:39.083278     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:39 remote-control-plane kubelet[287]: E0817 17:50:39.183947     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:39 remote-control-plane kubelet[287]: E0817 17:50:39.284233     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:39 remote-control-plane kubelet[287]: E0817 17:50:39.384862     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:39 remote-control-plane kubelet[287]: E0817 17:50:39.485468     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:39 remote-control-plane kubelet[287]: E0817 17:50:39.587530     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:39 remote-control-plane kubelet[287]: E0817 17:50:39.688520     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:39 remote-control-plane kubelet[287]: E0817 17:50:39.789514     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:39 remote-control-plane kubelet[287]: E0817 17:50:39.889630     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:39 remote-control-plane kubelet[287]: E0817 17:50:39.989934     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:40 remote-control-plane kubelet[287]: E0817 17:50:40.037283     287 eviction_manager.go:255] "Eviction manager: failed to get summary stats" err="failed to get node info: node \"remote-control-plane\" not found"
Aug 17 17:50:40 remote-control-plane kubelet[287]: E0817 17:50:40.042164     287 kubelet.go:2211] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized"
Aug 17 17:50:40 remote-control-plane kubelet[287]: E0817 17:50:40.090512     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:40 remote-control-plane kubelet[287]: E0817 17:50:40.191443     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:40 remote-control-plane kubelet[287]: E0817 17:50:40.292433     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:40 remote-control-plane kubelet[287]: E0817 17:50:40.392623     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:40 remote-control-plane kubelet[287]: E0817 17:50:40.493499     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:40 remote-control-plane kubelet[287]: E0817 17:50:40.594119     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:40 remote-control-plane kubelet[287]: E0817 17:50:40.694835     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:40 remote-control-plane kubelet[287]: E0817 17:50:40.795257     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:40 remote-control-plane kubelet[287]: E0817 17:50:40.895929     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:40 remote-control-plane kubelet[287]: E0817 17:50:40.996930     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:41 remote-control-plane kubelet[287]: E0817 17:50:41.097963     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:41 remote-control-plane kubelet[287]: E0817 17:50:41.198561     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:41 remote-control-plane kubelet[287]: E0817 17:50:41.299738     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:41 remote-control-plane kubelet[287]: E0817 17:50:41.400313     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:41 remote-control-plane kubelet[287]: E0817 17:50:41.500534     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:41 remote-control-plane kubelet[287]: E0817 17:50:41.601745     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:41 remote-control-plane kubelet[287]: E0817 17:50:41.702713     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:41 remote-control-plane kubelet[287]: E0817 17:50:41.783136     287 nodelease.go:49] "Failed to get node when trying to set owner ref to the node lease" err="nodes \"remote-control-plane\" not found" node="remote-control-plane"
Aug 17 17:50:41 remote-control-plane kubelet[287]: E0817 17:50:41.803652     287 kubelet.go:2291] "Error getting node" err="node \"remote-control-plane\" not found"
Aug 17 17:50:41 remote-control-plane kubelet[287]: I0817 17:50:41.899247     287 kubelet_node_status.go:74] "Successfully registered node" node="remote-control-plane"
Aug 17 17:50:41 remote-control-plane kubelet[287]: E0817 17:50:41.932654     287 event.go:264] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"remote-control-plane.169c295997d3b608", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"remote-control-plane", UID:"remote-control-plane", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"Starting", Message:"Starting kubelet.", Source:v1.EventSource{Component:"kubelet", Host:"remote-control-plane"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xc03f1b997a410408, ext:8650794501, loc:(*time.Location)(0x74aba00)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xc03f1b997a410408, ext:8650794501, loc:(*time.Location)(0x74aba00)}}, Count:1, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'namespaces "default" not found' (will not retry!)
Aug 17 17:50:41 remote-control-plane kubelet[287]: E0817 17:50:41.996684     287 event.go:264] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"remote-control-plane.169c29599aa25088", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"remote-control-plane", UID:"remote-control-plane", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientMemory", Message:"Node remote-control-plane status is now: NodeHasSufficientMemory", Source:v1.EventSource{Component:"kubelet", Host:"remote-control-plane"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xc03f1b998174d488, ext:8697885401, loc:(*time.Location)(0x74aba00)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xc03f1b998174d488, ext:8697885401, loc:(*time.Location)(0x74aba00)}}, Count:1, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'namespaces "default" not found' (will not retry!)
Aug 17 17:50:42 remote-control-plane kubelet[287]: E0817 17:50:42.052796     287 event.go:264] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"remote-control-plane.169c29599aa2ae48", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"remote-control-plane", UID:"remote-control-plane", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasNoDiskPressure", Message:"Node remote-control-plane status is now: NodeHasNoDiskPressure", Source:v1.EventSource{Component:"kubelet", Host:"remote-control-plane"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xc03f1b9981753248, ext:8697910301, loc:(*time.Location)(0x74aba00)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xc03f1b9981753248, ext:8697910301, loc:(*time.Location)(0x74aba00)}}, Count:1, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'namespaces "default" not found' (will not retry!)
Aug 17 17:50:42 remote-control-plane kubelet[287]: E0817 17:50:42.108902     287 event.go:264] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"remote-control-plane.169c29599aa2fdf8", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"remote-control-plane", UID:"remote-control-plane", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientPID", Message:"Node remote-control-plane status is now: NodeHasSufficientPID", Source:v1.EventSource{Component:"kubelet", Host:"remote-control-plane"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xc03f1b99817581f8, ext:8697929201, loc:(*time.Location)(0x74aba00)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xc03f1b99817581f8, ext:8697929201, loc:(*time.Location)(0x74aba00)}}, Count:1, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'namespaces "default" not found' (will not retry!)
Aug 17 17:50:42 remote-control-plane kubelet[287]: E0817 17:50:42.165129     287 event.go:264] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"remote-control-plane.169c29599b548f00", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"remote-control-plane", UID:"remote-control-plane", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeAllocatableEnforced", Message:"Updated Node Allocatable limit across pods", Source:v1.EventSource{Component:"kubelet", Host:"remote-control-plane"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xc03f1b9982271300, ext:8709565701, loc:(*time.Location)(0x74aba00)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xc03f1b9982271300, ext:8709565701, loc:(*time.Location)(0x74aba00)}}, Count:1, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'namespaces "default" not found' (will not retry!)
Aug 17 17:50:42 remote-control-plane kubelet[287]: E0817 17:50:42.222995     287 event.go:264] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"remote-control-plane.169c29599aa25088", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"remote-control-plane", UID:"remote-control-plane", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientMemory", Message:"Node remote-control-plane status is now: NodeHasSufficientMemory", Source:v1.EventSource{Component:"kubelet", Host:"remote-control-plane"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xc03f1b998174d488, ext:8697885401, loc:(*time.Location)(0x74aba00)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xc03f1b998519d7b4, ext:8759030701, loc:(*time.Location)(0x74aba00)}}, Count:2, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'namespaces "default" not found' (will not retry!)
Aug 17 17:50:42 remote-control-plane kubelet[287]: E0817 17:50:42.282249     287 event.go:264] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"remote-control-plane.169c29599aa2ae48", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"remote-control-plane", UID:"remote-control-plane", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasNoDiskPressure", Message:"Node remote-control-plane status is now: NodeHasNoDiskPressure", Source:v1.EventSource{Component:"kubelet", Host:"remote-control-plane"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xc03f1b9981753248, ext:8697910301, loc:(*time.Location)(0x74aba00)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xc03f1b99851a2250, ext:8759050001, loc:(*time.Location)(0x74aba00)}}, Count:2, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'namespaces "default" not found' (will not retry!)
Aug 17 17:50:42 remote-control-plane kubelet[287]: E0817 17:50:42.340803     287 event.go:264] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"remote-control-plane.169c29599aa2fdf8", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"remote-control-plane", UID:"remote-control-plane", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientPID", Message:"Node remote-control-plane status is now: NodeHasSufficientPID", Source:v1.EventSource{Component:"kubelet", Host:"remote-control-plane"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xc03f1b99817581f8, ext:8697929201, loc:(*time.Location)(0x74aba00)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xc03f1b99851a7bc4, ext:8759072801, loc:(*time.Location)(0x74aba00)}}, Count:2, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'namespaces "default" not found' (will not retry!)
Aug 17 17:50:42 remote-control-plane kubelet[287]: E0817 17:50:42.407198     287 event.go:264] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"remote-control-plane.169c29599aa25088", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"remote-control-plane", UID:"remote-control-plane", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientMemory", Message:"Node remote-control-plane status is now: NodeHasSufficientMemory", Source:v1.EventSource{Component:"kubelet", Host:"remote-control-plane"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xc03f1b998174d488, ext:8697885401, loc:(*time.Location)(0x74aba00)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xc03f1b999135ca6c, ext:8962190101, loc:(*time.Location)(0x74aba00)}}, Count:3, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'namespaces "default" not found' (will not retry!)
Aug 17 17:50:42 remote-control-plane kubelet[287]: I0817 17:50:42.752874     287 apiserver.go:52] "Watching apiserver"
Aug 17 17:50:42 remote-control-plane kubelet[287]: E0817 17:50:42.788150     287 event.go:264] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"remote-control-plane.169c29599aa2ae48", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"remote-control-plane", UID:"remote-control-plane", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasNoDiskPressure", Message:"Node remote-control-plane status is now: NodeHasNoDiskPressure", Source:v1.EventSource{Component:"kubelet", Host:"remote-control-plane"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xc03f1b9981753248, ext:8697910301, loc:(*time.Location)(0x74aba00)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xc03f1b9991362570, ext:8962211501, loc:(*time.Location)(0x74aba00)}}, Count:3, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'namespaces "default" not found' (will not retry!)
Aug 17 17:50:42 remote-control-plane kubelet[287]: I0817 17:50:42.817763     287 reconciler.go:157] "Reconciler: start to sync state"
Aug 17 17:50:43 remote-control-plane kubelet[287]: E0817 17:50:43.155691     287 event.go:264] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"remote-control-plane.169c29599aa2fdf8", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"remote-control-plane", UID:"remote-control-plane", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientPID", Message:"Node remote-control-plane status is now: NodeHasSufficientPID", Source:v1.EventSource{Component:"kubelet", Host:"remote-control-plane"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xc03f1b99817581f8, ext:8697929201, loc:(*time.Location)(0x74aba00)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xc03f1b999136732c, ext:8962231301, loc:(*time.Location)(0x74aba00)}}, Count:3, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'namespaces "default" not found' (will not retry!)
Aug 17 17:50:45 remote-control-plane kubelet[287]: E0817 17:50:45.009263     287 kubelet.go:2211] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized"
Aug 17 17:50:45 remote-control-plane systemd[1]: Stopping kubelet: The Kubernetes Node Agent...
Aug 17 17:50:45 remote-control-plane kubelet[287]: I0817 17:50:45.018478     287 dynamic_cafile_content.go:182] Shutting down client-ca-bundle::/etc/kubernetes/pki/ca.crt
Aug 17 17:50:45 remote-control-plane systemd[1]: kubelet.service: Succeeded.
Aug 17 17:50:45 remote-control-plane systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
Aug 17 17:50:45 remote-control-plane systemd[1]: Starting kubelet: The Kubernetes Node Agent...
Aug 17 17:50:45 remote-control-plane systemd[1]: Started kubelet: The Kubernetes Node Agent.
Aug 17 17:50:45 remote-control-plane kubelet[785]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Aug 17 17:50:45 remote-control-plane kubelet[785]: Flag --provider-id has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Aug 17 17:50:45 remote-control-plane kubelet[785]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Aug 17 17:50:45 remote-control-plane kubelet[785]: Flag --cgroup-root has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Aug 17 17:50:45 remote-control-plane kubelet[785]: I0817 17:50:45.200288     785 server.go:197] "Warning: For remote container runtime, --pod-infra-container-image is ignored in kubelet, which should be set in that remote runtime instead"
Aug 17 17:50:45 remote-control-plane kubelet[785]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Aug 17 17:50:45 remote-control-plane kubelet[785]: Flag --provider-id has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Aug 17 17:50:45 remote-control-plane kubelet[785]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Aug 17 17:50:45 remote-control-plane kubelet[785]: Flag --cgroup-root has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Aug 17 17:50:45 remote-control-plane kubelet[785]: I0817 17:50:45.214603     785 server.go:440] "Kubelet version" kubeletVersion="v1.21.1"
Aug 17 17:50:45 remote-control-plane kubelet[785]: I0817 17:50:45.215275     785 server.go:851] "Client rotation is on, will bootstrap in background"
Aug 17 17:50:45 remote-control-plane kubelet[785]: I0817 17:50:45.217121     785 certificate_store.go:130] Loading cert/key pair from "/var/lib/kubelet/pki/kubelet-client-current.pem".
Aug 17 17:50:45 remote-control-plane kubelet[785]: I0817 17:50:45.218513     785 dynamic_cafile_content.go:167] Starting client-ca-bundle::/etc/kubernetes/pki/ca.crt
Aug 17 17:50:50 remote-control-plane kubelet[785]: W0817 17:50:50.228259     785 sysinfo.go:203] Nodes topology is not available, providing CPU topology
Aug 17 17:50:50 remote-control-plane kubelet[785]: I0817 17:50:50.241080     785 container_manager_linux.go:278] "Container manager verified user specified cgroup-root exists" cgroupRoot=[kubelet]
Aug 17 17:50:50 remote-control-plane kubelet[785]: I0817 17:50:50.241465     785 container_manager_linux.go:283] "Creating Container Manager object based on Node Config" nodeConfig={RuntimeCgroupsName: SystemCgroupsName: KubeletCgroupsName: ContainerRuntime:remote CgroupsPerQOS:true CgroupRoot:/kubelet CgroupDriver:cgroupfs KubeletRootDir:/var/lib/kubelet ProtectKernelDefaults:false NodeAllocatableConfig:{KubeReservedCgroupName: SystemReservedCgroupName: ReservedSystemCPUs: EnforceNodeAllocatable:map[pods:{}] KubeReserved:map[] SystemReserved:map[] HardEvictionThresholds:[]} QOSReserved:map[] ExperimentalCPUManagerPolicy:none ExperimentalTopologyManagerScope:container ExperimentalCPUManagerReconcilePeriod:10s ExperimentalMemoryManagerPolicy:None ExperimentalMemoryManagerReservedMemory:[] ExperimentalPodPidsLimit:-1 EnforceCPULimits:true CPUCFSQuotaPeriod:100ms ExperimentalTopologyManagerPolicy:none}
Aug 17 17:50:50 remote-control-plane kubelet[785]: I0817 17:50:50.241515     785 topology_manager.go:120] "Creating topology manager with policy per scope" topologyPolicyName="none" topologyScopeName="container"
Aug 17 17:50:50 remote-control-plane kubelet[785]: I0817 17:50:50.241550     785 container_manager_linux.go:314] "Initializing Topology Manager" policy="none" scope="container"
Aug 17 17:50:50 remote-control-plane kubelet[785]: I0817 17:50:50.241574     785 container_manager_linux.go:319] "Creating device plugin manager" devicePluginEnabled=true
Aug 17 17:50:50 remote-control-plane kubelet[785]: I0817 17:50:50.241823     785 remote_runtime.go:62] parsed scheme: ""
Aug 17 17:50:50 remote-control-plane kubelet[785]: I0817 17:50:50.241845     785 remote_runtime.go:62] scheme "" not registered, fallback to default scheme
Aug 17 17:50:50 remote-control-plane kubelet[785]: I0817 17:50:50.241878     785 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{/run/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}
Aug 17 17:50:50 remote-control-plane kubelet[785]: I0817 17:50:50.242016     785 clientconn.go:948] ClientConn switching balancer to "pick_first"
Aug 17 17:50:50 remote-control-plane kubelet[785]: I0817 17:50:50.242102     785 remote_image.go:50] parsed scheme: ""
Aug 17 17:50:50 remote-control-plane kubelet[785]: I0817 17:50:50.242118     785 remote_image.go:50] scheme "" not registered, fallback to default scheme
Aug 17 17:50:50 remote-control-plane kubelet[785]: I0817 17:50:50.242375     785 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{/run/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}
Aug 17 17:50:50 remote-control-plane kubelet[785]: I0817 17:50:50.242398     785 clientconn.go:948] ClientConn switching balancer to "pick_first"
Aug 17 17:50:50 remote-control-plane kubelet[785]: I0817 17:50:50.242623     785 kubelet.go:404] "Attempting to sync node with API server"
Aug 17 17:50:50 remote-control-plane kubelet[785]: I0817 17:50:50.242654     785 kubelet.go:272] "Adding static pod path" path="/etc/kubernetes/manifests"
Aug 17 17:50:50 remote-control-plane kubelet[785]: I0817 17:50:50.243478     785 kubelet.go:283] "Adding apiserver pod source"
Aug 17 17:50:50 remote-control-plane kubelet[785]: I0817 17:50:50.243553     785 apiserver.go:42] "Waiting for node sync before watching apiserver pods"
Aug 17 17:50:50 remote-control-plane kubelet[785]: I0817 17:50:50.248261     785 kuberuntime_manager.go:222] "Container runtime initialized" containerRuntime="containerd" version="v1.5.1" apiVersion="v1alpha2"
Aug 17 17:50:51 remote-control-plane kubelet[785]: I0817 17:50:51.247411     785 apiserver.go:52] "Watching apiserver"
Aug 17 17:50:54 remote-control-plane kubelet[785]: E0817 17:50:54.510761     785 aws_credentials.go:77] while getting AWS credentials NoCredentialProviders: no valid providers in chain. Deprecated.
Aug 17 17:50:54 remote-control-plane kubelet[785]:         For verbose messaging see aws.Config.CredentialsChainVerboseErrors
Aug 17 17:50:54 remote-control-plane kubelet[785]: I0817 17:50:54.511678     785 server.go:1190] "Started kubelet"
Aug 17 17:50:54 remote-control-plane kubelet[785]: I0817 17:50:54.512462     785 server.go:149] "Starting to listen" address="0.0.0.0" port=10250
Aug 17 17:50:54 remote-control-plane kubelet[785]: I0817 17:50:54.515026     785 server.go:405] "Adding debug handlers to kubelet server"
Aug 17 17:50:54 remote-control-plane kubelet[785]: I0817 17:50:54.518750     785 fs_resource_analyzer.go:67] "Starting FS ResourceAnalyzer"
Aug 17 17:50:54 remote-control-plane kubelet[785]: I0817 17:50:54.519019     785 volume_manager.go:271] "Starting Kubelet Volume Manager"
Aug 17 17:50:54 remote-control-plane kubelet[785]: I0817 17:50:54.519275     785 desired_state_of_world_populator.go:141] "Desired state populator starts to run"
Aug 17 17:50:54 remote-control-plane kubelet[785]: E0817 17:50:54.522485     785 kubelet.go:2211] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized"
Aug 17 17:50:54 remote-control-plane kubelet[785]: I0817 17:50:54.522663     785 client.go:86] parsed scheme: "unix"
Aug 17 17:50:54 remote-control-plane kubelet[785]: I0817 17:50:54.522684     785 client.go:86] scheme "unix" not registered, fallback to default scheme
Aug 17 17:50:54 remote-control-plane kubelet[785]: I0817 17:50:54.522777     785 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}
Aug 17 17:50:54 remote-control-plane kubelet[785]: I0817 17:50:54.522800     785 clientconn.go:948] ClientConn switching balancer to "pick_first"
Aug 17 17:50:54 remote-control-plane kubelet[785]: I0817 17:50:54.626117     785 kubelet_node_status.go:71] "Attempting to register node" node="remote-control-plane"
Aug 17 17:50:54 remote-control-plane kubelet[785]: I0817 17:50:54.652486     785 kubelet_node_status.go:109] "Node was previously registered" node="remote-control-plane"
Aug 17 17:50:54 remote-control-plane kubelet[785]: I0817 17:50:54.652601     785 kubelet_node_status.go:74] "Successfully registered node" node="remote-control-plane"
Aug 17 17:50:54 remote-control-plane kubelet[785]: I0817 17:50:54.750267     785 kubelet_network_linux.go:56] "Initialized protocol iptables rules." protocol=IPv4
Aug 17 17:50:54 remote-control-plane kubelet[785]: I0817 17:50:54.803073     785 cpu_manager.go:199] "Starting CPU manager" policy="none"
Aug 17 17:50:54 remote-control-plane kubelet[785]: I0817 17:50:54.803116     785 cpu_manager.go:200] "Reconciling" reconcilePeriod="10s"
Aug 17 17:50:54 remote-control-plane kubelet[785]: I0817 17:50:54.803143     785 state_mem.go:36] "Initialized new in-memory state store"
Aug 17 17:50:54 remote-control-plane kubelet[785]: I0817 17:50:54.803322     785 state_mem.go:88] "Updated default CPUSet" cpuSet=""
Aug 17 17:50:54 remote-control-plane kubelet[785]: I0817 17:50:54.803346     785 state_mem.go:96] "Updated CPUSet assignments" assignments=map[]
Aug 17 17:50:54 remote-control-plane kubelet[785]: I0817 17:50:54.803365     785 policy_none.go:44] "None policy: Start"
Aug 17 17:50:54 remote-control-plane kubelet[785]: I0817 17:50:54.804540     785 manager.go:600] "Failed to retrieve checkpoint" checkpoint="kubelet_internal_checkpoint" err="checkpoint is not found"
Aug 17 17:50:54 remote-control-plane kubelet[785]: I0817 17:50:54.806634     785 plugin_manager.go:114] "Starting Kubelet Plugin Manager"
Aug 17 17:50:54 remote-control-plane kubelet[785]: I0817 17:50:54.902343     785 kubelet_network_linux.go:56] "Initialized protocol iptables rules." protocol=IPv6
Aug 17 17:50:54 remote-control-plane kubelet[785]: I0817 17:50:54.902390     785 status_manager.go:157] "Starting to sync pod status with apiserver"
Aug 17 17:50:54 remote-control-plane kubelet[785]: I0817 17:50:54.902415     785 kubelet.go:1846] "Starting kubelet main sync loop"
Aug 17 17:50:54 remote-control-plane kubelet[785]: E0817 17:50:54.902478     785 kubelet.go:1870] "Skipping pod synchronization" err="PLEG is not healthy: pleg has yet to be successful"
Aug 17 17:50:55 remote-control-plane kubelet[785]: I0817 17:50:55.003514     785 topology_manager.go:187] "Topology Admit Handler"
Aug 17 17:50:55 remote-control-plane kubelet[785]: I0817 17:50:55.003830     785 topology_manager.go:187] "Topology Admit Handler"
Aug 17 17:50:55 remote-control-plane kubelet[785]: I0817 17:50:55.004129     785 topology_manager.go:187] "Topology Admit Handler"
Aug 17 17:50:55 remote-control-plane kubelet[785]: I0817 17:50:55.004331     785 topology_manager.go:187] "Topology Admit Handler"
Aug 17 17:50:55 remote-control-plane kubelet[785]: I0817 17:50:55.021314     785 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"etcd-data\" (UniqueName: \"kubernetes.io/host-path/464f70cc19489045f3a12d8fc40c8986-etcd-data\") pod \"etcd-remote-control-plane\" (UID: \"464f70cc19489045f3a12d8fc40c8986\") "
Aug 17 17:50:55 remote-control-plane kubelet[785]: I0817 17:50:55.021582     785 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"etc-ca-certificates\" (UniqueName: \"kubernetes.io/host-path/00413c9191df709893361d18bc0fcc16-etc-ca-certificates\") pod \"kube-controller-manager-remote-control-plane\" (UID: \"00413c9191df709893361d18bc0fcc16\") "
Aug 17 17:50:55 remote-control-plane kubelet[785]: I0817 17:50:55.021755     785 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"flexvolume-dir\" (UniqueName: \"kubernetes.io/host-path/00413c9191df709893361d18bc0fcc16-flexvolume-dir\") pod \"kube-controller-manager-remote-control-plane\" (UID: \"00413c9191df709893361d18bc0fcc16\") "
Aug 17 17:50:55 remote-control-plane kubelet[785]: I0817 17:50:55.021904     785 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"kubeconfig\" (UniqueName: \"kubernetes.io/host-path/00413c9191df709893361d18bc0fcc16-kubeconfig\") pod \"kube-controller-manager-remote-control-plane\" (UID: \"00413c9191df709893361d18bc0fcc16\") "
Aug 17 17:50:55 remote-control-plane kubelet[785]: I0817 17:50:55.022050     785 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"usr-local-share-ca-certificates\" (UniqueName: \"kubernetes.io/host-path/00413c9191df709893361d18bc0fcc16-usr-local-share-ca-certificates\") pod \"kube-controller-manager-remote-control-plane\" (UID: \"00413c9191df709893361d18bc0fcc16\") "
Aug 17 17:50:55 remote-control-plane kubelet[785]: I0817 17:50:55.022259     785 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"usr-share-ca-certificates\" (UniqueName: \"kubernetes.io/host-path/00413c9191df709893361d18bc0fcc16-usr-share-ca-certificates\") pod \"kube-controller-manager-remote-control-plane\" (UID: \"00413c9191df709893361d18bc0fcc16\") "
Aug 17 17:50:55 remote-control-plane kubelet[785]: I0817 17:50:55.022413     785 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"etcd-certs\" (UniqueName: \"kubernetes.io/host-path/464f70cc19489045f3a12d8fc40c8986-etcd-certs\") pod \"etcd-remote-control-plane\" (UID: \"464f70cc19489045f3a12d8fc40c8986\") "
Aug 17 17:50:55 remote-control-plane kubelet[785]: I0817 17:50:55.022544     785 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"ca-certs\" (UniqueName: \"kubernetes.io/host-path/9b0a6fe1ae446c8289ca29f8bcbb3394-ca-certs\") pod \"kube-apiserver-remote-control-plane\" (UID: \"9b0a6fe1ae446c8289ca29f8bcbb3394\") "
Aug 17 17:50:55 remote-control-plane kubelet[785]: I0817 17:50:55.022694     785 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"k8s-certs\" (UniqueName: \"kubernetes.io/host-path/9b0a6fe1ae446c8289ca29f8bcbb3394-k8s-certs\") pod \"kube-apiserver-remote-control-plane\" (UID: \"9b0a6fe1ae446c8289ca29f8bcbb3394\") "
Aug 17 17:50:55 remote-control-plane kubelet[785]: I0817 17:50:55.022837     785 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"usr-share-ca-certificates\" (UniqueName: \"kubernetes.io/host-path/9b0a6fe1ae446c8289ca29f8bcbb3394-usr-share-ca-certificates\") pod \"kube-apiserver-remote-control-plane\" (UID: \"9b0a6fe1ae446c8289ca29f8bcbb3394\") "
Aug 17 17:50:55 remote-control-plane kubelet[785]: I0817 17:50:55.023632     785 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"k8s-certs\" (UniqueName: \"kubernetes.io/host-path/00413c9191df709893361d18bc0fcc16-k8s-certs\") pod \"kube-controller-manager-remote-control-plane\" (UID: \"00413c9191df709893361d18bc0fcc16\") "
Aug 17 17:50:55 remote-control-plane kubelet[785]: I0817 17:50:55.024276     785 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"ca-certs\" (UniqueName: \"kubernetes.io/host-path/00413c9191df709893361d18bc0fcc16-ca-certs\") pod \"kube-controller-manager-remote-control-plane\" (UID: \"00413c9191df709893361d18bc0fcc16\") "
Aug 17 17:50:55 remote-control-plane kubelet[785]: I0817 17:50:55.024878     785 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"etc-ca-certificates\" (UniqueName: \"kubernetes.io/host-path/9b0a6fe1ae446c8289ca29f8bcbb3394-etc-ca-certificates\") pod \"kube-apiserver-remote-control-plane\" (UID: \"9b0a6fe1ae446c8289ca29f8bcbb3394\") "
Aug 17 17:50:55 remote-control-plane kubelet[785]: I0817 17:50:55.027360     785 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"usr-local-share-ca-certificates\" (UniqueName: \"kubernetes.io/host-path/9b0a6fe1ae446c8289ca29f8bcbb3394-usr-local-share-ca-certificates\") pod \"kube-apiserver-remote-control-plane\" (UID: \"9b0a6fe1ae446c8289ca29f8bcbb3394\") "
Aug 17 17:50:55 remote-control-plane kubelet[785]: I0817 17:50:55.027656     785 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"kubeconfig\" (UniqueName: \"kubernetes.io/host-path/91fcc6c180befeefc8bb69fd100aff4d-kubeconfig\") pod \"kube-scheduler-remote-control-plane\" (UID: \"91fcc6c180befeefc8bb69fd100aff4d\") "
Aug 17 17:50:55 remote-control-plane kubelet[785]: I0817 17:50:55.027806     785 reconciler.go:157] "Reconciler: start to sync state"
Aug 17 17:50:59 remote-control-plane kubelet[785]: E0817 17:50:59.806310     785 kubelet.go:2211] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized"
Aug 17 17:51:00 remote-control-plane kubelet[785]: I0817 17:51:00.167755     785 kuberuntime_manager.go:1044] "Updating runtime config through cri with podcidr" CIDR="10.30.0.0/24"
Aug 17 17:51:00 remote-control-plane kubelet[785]: I0817 17:51:00.168446     785 kubelet_network.go:76] "Updating Pod CIDR" originalPodCIDR="" newPodCIDR="10.30.0.0/24"
Aug 17 17:51:00 remote-control-plane kubelet[785]: E0817 17:51:00.169050     785 kubelet.go:2211] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized"
Aug 17 17:51:00 remote-control-plane kubelet[785]: I0817 17:51:00.636954     785 topology_manager.go:187] "Topology Admit Handler"
Aug 17 17:51:00 remote-control-plane kubelet[785]: I0817 17:51:00.667769     785 topology_manager.go:187] "Topology Admit Handler"
Aug 17 17:51:00 remote-control-plane kubelet[785]: W0817 17:51:00.677534     785 container.go:586] Failed to update stats for container "/kubelet/kubepods/besteffort/pod703f6444-43cd-49ac-9d50-e6badc1279b9": /sys/fs/cgroup/cpuset/kubelet/kubepods/besteffort/pod703f6444-43cd-49ac-9d50-e6badc1279b9/cpuset.mems found to be empty, continuing to push stats
Aug 17 17:51:00 remote-control-plane kubelet[785]: I0817 17:51:00.692736     785 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"cni-cfg\" (UniqueName: \"kubernetes.io/host-path/c33b3ca2-7d37-4ecf-a2bc-5aaebc13d79d-cni-cfg\") pod \"kindnet-l4dm5\" (UID: \"c33b3ca2-7d37-4ecf-a2bc-5aaebc13d79d\") "
Aug 17 17:51:00 remote-control-plane kubelet[785]: I0817 17:51:00.692967     785 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"xtables-lock\" (UniqueName: \"kubernetes.io/host-path/c33b3ca2-7d37-4ecf-a2bc-5aaebc13d79d-xtables-lock\") pod \"kindnet-l4dm5\" (UID: \"c33b3ca2-7d37-4ecf-a2bc-5aaebc13d79d\") "
Aug 17 17:51:00 remote-control-plane kubelet[785]: I0817 17:51:00.693126     785 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"xtables-lock\" (UniqueName: \"kubernetes.io/host-path/703f6444-43cd-49ac-9d50-e6badc1279b9-xtables-lock\") pod \"kube-proxy-hbpmz\" (UID: \"703f6444-43cd-49ac-9d50-e6badc1279b9\") "
Aug 17 17:51:00 remote-control-plane kubelet[785]: I0817 17:51:00.693171     785 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"kube-api-access-265nt\" (UniqueName: \"kubernetes.io/projected/c33b3ca2-7d37-4ecf-a2bc-5aaebc13d79d-kube-api-access-265nt\") pod \"kindnet-l4dm5\" (UID: \"c33b3ca2-7d37-4ecf-a2bc-5aaebc13d79d\") "
Aug 17 17:51:00 remote-control-plane kubelet[785]: I0817 17:51:00.693292     785 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"lib-modules\" (UniqueName: \"kubernetes.io/host-path/c33b3ca2-7d37-4ecf-a2bc-5aaebc13d79d-lib-modules\") pod \"kindnet-l4dm5\" (UID: \"c33b3ca2-7d37-4ecf-a2bc-5aaebc13d79d\") "
Aug 17 17:51:00 remote-control-plane kubelet[785]: I0817 17:51:00.693439     785 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"kube-proxy\" (UniqueName: \"kubernetes.io/configmap/703f6444-43cd-49ac-9d50-e6badc1279b9-kube-proxy\") pod \"kube-proxy-hbpmz\" (UID: \"703f6444-43cd-49ac-9d50-e6badc1279b9\") "
Aug 17 17:51:00 remote-control-plane kubelet[785]: I0817 17:51:00.693535     785 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"lib-modules\" (UniqueName: \"kubernetes.io/host-path/703f6444-43cd-49ac-9d50-e6badc1279b9-lib-modules\") pod \"kube-proxy-hbpmz\" (UID: \"703f6444-43cd-49ac-9d50-e6badc1279b9\") "
Aug 17 17:51:00 remote-control-plane kubelet[785]: I0817 17:51:00.693576     785 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"kube-api-access-6g2ts\" (UniqueName: \"kubernetes.io/projected/703f6444-43cd-49ac-9d50-e6badc1279b9-kube-api-access-6g2ts\") pod \"kube-proxy-hbpmz\" (UID: \"703f6444-43cd-49ac-9d50-e6badc1279b9\") "
Aug 17 17:51:00 remote-control-plane kubelet[785]: E0817 17:51:00.840142     785 projected.go:293] Couldn't get configMap kube-system/kube-root-ca.crt: configmap "kube-root-ca.crt" not found
Aug 17 17:51:00 remote-control-plane kubelet[785]: E0817 17:51:00.840203     785 projected.go:199] Error preparing data for projected volume kube-api-access-6g2ts for pod kube-system/kube-proxy-hbpmz: configmap "kube-root-ca.crt" not found
Aug 17 17:51:00 remote-control-plane kubelet[785]: E0817 17:51:00.840385     785 nestedpendingoperations.go:301] Operation for "{volumeName:kubernetes.io/projected/703f6444-43cd-49ac-9d50-e6badc1279b9-kube-api-access-6g2ts podName:703f6444-43cd-49ac-9d50-e6badc1279b9 nodeName:}" failed. No retries permitted until 2021-08-17 17:51:01.3403393 +0000 UTC m=+16.283014301 (durationBeforeRetry 500ms). Error: "MountVolume.SetUp failed for volume \"kube-api-access-6g2ts\" (UniqueName: \"kubernetes.io/projected/703f6444-43cd-49ac-9d50-e6badc1279b9-kube-api-access-6g2ts\") pod \"kube-proxy-hbpmz\" (UID: \"703f6444-43cd-49ac-9d50-e6badc1279b9\") : configmap \"kube-root-ca.crt\" not found"
Aug 17 17:51:00 remote-control-plane kubelet[785]: E0817 17:51:00.842618     785 projected.go:293] Couldn't get configMap kube-system/kube-root-ca.crt: configmap "kube-root-ca.crt" not found
Aug 17 17:51:00 remote-control-plane kubelet[785]: E0817 17:51:00.842667     785 projected.go:199] Error preparing data for projected volume kube-api-access-265nt for pod kube-system/kindnet-l4dm5: configmap "kube-root-ca.crt" not found
Aug 17 17:51:00 remote-control-plane kubelet[785]: E0817 17:51:00.842745     785 nestedpendingoperations.go:301] Operation for "{volumeName:kubernetes.io/projected/c33b3ca2-7d37-4ecf-a2bc-5aaebc13d79d-kube-api-access-265nt podName:c33b3ca2-7d37-4ecf-a2bc-5aaebc13d79d nodeName:}" failed. No retries permitted until 2021-08-17 17:51:01.342717 +0000 UTC m=+16.285392501 (durationBeforeRetry 500ms). Error: "MountVolume.SetUp failed for volume \"kube-api-access-265nt\" (UniqueName: \"kubernetes.io/projected/c33b3ca2-7d37-4ecf-a2bc-5aaebc13d79d-kube-api-access-265nt\") pod \"kindnet-l4dm5\" (UID: \"c33b3ca2-7d37-4ecf-a2bc-5aaebc13d79d\") : configmap \"kube-root-ca.crt\" not found"
Aug 17 17:51:04 remote-control-plane kubelet[785]: E0817 17:51:04.809172     785 kubelet.go:2211] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized"
Aug 17 17:51:04 remote-control-plane kubelet[785]: E0817 17:51:04.949894     785 cadvisor_stats_provider.go:415] "Partial failure issuing cadvisor.ContainerInfoV2" err="partial failures: [\"/kubelet/kubepods/besteffort/pod703f6444-43cd-49ac-9d50-e6badc1279b9\": RecentStats: unable to find data in memory cache]"
Aug 17 17:51:16 remote-control-plane kubelet[785]: I0817 17:51:16.355748     785 topology_manager.go:187] "Topology Admit Handler"
Aug 17 17:51:16 remote-control-plane kubelet[785]: I0817 17:51:16.405150     785 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"tmp-dir\" (UniqueName: \"kubernetes.io/empty-dir/e03a8bf0-e5b7-438d-9b99-38344a80e6e4-tmp-dir\") pod \"metrics-server-99b5b5fc6-9qhnd\" (UID: \"e03a8bf0-e5b7-438d-9b99-38344a80e6e4\") "
Aug 17 17:51:16 remote-control-plane kubelet[785]: I0817 17:51:16.405397     785 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"kube-api-access-84nq6\" (UniqueName: \"kubernetes.io/projected/e03a8bf0-e5b7-438d-9b99-38344a80e6e4-kube-api-access-84nq6\") pod \"metrics-server-99b5b5fc6-9qhnd\" (UID: \"e03a8bf0-e5b7-438d-9b99-38344a80e6e4\") "
Aug 17 17:51:19 remote-control-plane kubelet[785]: I0817 17:51:19.146248     785 topology_manager.go:187] "Topology Admit Handler"
Aug 17 17:51:19 remote-control-plane kubelet[785]: I0817 17:51:19.146467     785 topology_manager.go:187] "Topology Admit Handler"
Aug 17 17:51:19 remote-control-plane kubelet[785]: I0817 17:51:19.146870     785 topology_manager.go:187] "Topology Admit Handler"
Aug 17 17:51:19 remote-control-plane kubelet[785]: I0817 17:51:19.235265     785 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"kube-api-access-69vk8\" (UniqueName: \"kubernetes.io/projected/1ab532dc-5d99-4dfc-87e3-92f9376b64fb-kube-api-access-69vk8\") pod \"coredns-558bd4d5db-hxcwx\" (UID: \"1ab532dc-5d99-4dfc-87e3-92f9376b64fb\") "
Aug 17 17:51:19 remote-control-plane kubelet[785]: I0817 17:51:19.235575     785 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"config-volume\" (UniqueName: \"kubernetes.io/configmap/ad08e964-a048-4b17-945e-768e47c8fb66-config-volume\") pod \"coredns-558bd4d5db-wd7r7\" (UID: \"ad08e964-a048-4b17-945e-768e47c8fb66\") "
Aug 17 17:51:19 remote-control-plane kubelet[785]: I0817 17:51:19.235794     785 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"config-volume\" (UniqueName: \"kubernetes.io/configmap/92bb4020-a040-4d36-8ce5-6f7f46670553-config-volume\") pod \"local-path-provisioner-547f784dff-prcrg\" (UID: \"92bb4020-a040-4d36-8ce5-6f7f46670553\") "
Aug 17 17:51:19 remote-control-plane kubelet[785]: I0817 17:51:19.235964     785 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"kube-api-access-tctwq\" (UniqueName: \"kubernetes.io/projected/92bb4020-a040-4d36-8ce5-6f7f46670553-kube-api-access-tctwq\") pod \"local-path-provisioner-547f784dff-prcrg\" (UID: \"92bb4020-a040-4d36-8ce5-6f7f46670553\") "
Aug 17 17:51:19 remote-control-plane kubelet[785]: I0817 17:51:19.236166     785 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"config-volume\" (UniqueName: \"kubernetes.io/configmap/1ab532dc-5d99-4dfc-87e3-92f9376b64fb-config-volume\") pod \"coredns-558bd4d5db-hxcwx\" (UID: \"1ab532dc-5d99-4dfc-87e3-92f9376b64fb\") "
Aug 17 17:51:19 remote-control-plane kubelet[785]: I0817 17:51:19.236540     785 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"kube-api-access-cfnbb\" (UniqueName: \"kubernetes.io/projected/ad08e964-a048-4b17-945e-768e47c8fb66-kube-api-access-cfnbb\") pod \"coredns-558bd4d5db-wd7r7\" (UID: \"ad08e964-a048-4b17-945e-768e47c8fb66\") "
Aug 17 17:51:20 remote-control-plane kubelet[785]: I0817 17:51:20.762181     785 topology_manager.go:187] "Topology Admit Handler"
Aug 17 17:51:20 remote-control-plane kubelet[785]: I0817 17:51:20.830452     785 topology_manager.go:187] "Topology Admit Handler"
Aug 17 17:51:20 remote-control-plane kubelet[785]: I0817 17:51:20.854999     785 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"kube-api-access-wbqwm\" (UniqueName: \"kubernetes.io/projected/a04cc055-082f-4188-875a-a1c259f7b496-kube-api-access-wbqwm\") pod \"speaker-dc9fp\" (UID: \"a04cc055-082f-4188-875a-a1c259f7b496\") "
Aug 17 17:51:20 remote-control-plane kubelet[785]: I0817 17:51:20.955408     785 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"kube-api-access-mqv7r\" (UniqueName: \"kubernetes.io/projected/bf7210da-ca95-45ca-9848-5faf2ed0d5dd-kube-api-access-mqv7r\") pod \"controller-fb659dc8-drf8f\" (UID: \"bf7210da-ca95-45ca-9848-5faf2ed0d5dd\") "
