WARNING: Error loading config file: /home/.docker/config.json: Invalid auth configuration file
-- Logs begin at Tue 2021-08-17 17:50:16 UTC, end at Tue 2021-08-17 17:51:30 UTC. --
Aug 17 17:50:16 external-control-plane systemd[1]: Condition check resulted in kubelet: The Kubernetes Node Agent being skipped.
Aug 17 17:50:21 external-control-plane systemd[1]: Starting kubelet: The Kubernetes Node Agent...
Aug 17 17:50:21 external-control-plane systemd[1]: Started kubelet: The Kubernetes Node Agent.
Aug 17 17:50:21 external-control-plane kubelet[304]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Aug 17 17:50:21 external-control-plane kubelet[304]: Flag --provider-id has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Aug 17 17:50:21 external-control-plane kubelet[304]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Aug 17 17:50:21 external-control-plane kubelet[304]: Flag --cgroup-root has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Aug 17 17:50:21 external-control-plane kubelet[304]: I0817 17:50:21.466730     304 server.go:197] "Warning: For remote container runtime, --pod-infra-container-image is ignored in kubelet, which should be set in that remote runtime instead"
Aug 17 17:50:21 external-control-plane kubelet[304]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Aug 17 17:50:21 external-control-plane kubelet[304]: Flag --provider-id has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Aug 17 17:50:21 external-control-plane kubelet[304]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Aug 17 17:50:21 external-control-plane kubelet[304]: Flag --cgroup-root has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Aug 17 17:50:22 external-control-plane kubelet[304]: I0817 17:50:22.066904     304 server.go:440] "Kubelet version" kubeletVersion="v1.21.1"
Aug 17 17:50:22 external-control-plane kubelet[304]: I0817 17:50:22.067588     304 server.go:851] "Client rotation is on, will bootstrap in background"
Aug 17 17:50:22 external-control-plane kubelet[304]: I0817 17:50:22.070597     304 dynamic_cafile_content.go:167] Starting client-ca-bundle::/etc/kubernetes/pki/ca.crt
Aug 17 17:50:22 external-control-plane kubelet[304]: E0817 17:50:22.079718     304 certificate_manager.go:437] Failed while requesting a signed certificate from the master: cannot create certificate signing request: Post "https://external-control-plane:6443/apis/certificates.k8s.io/v1/certificatesigningrequests": dial tcp 172.18.0.4:6443: connect: connection refused
Aug 17 17:50:24 external-control-plane kubelet[304]: E0817 17:50:24.088549     304 certificate_manager.go:437] Failed while requesting a signed certificate from the master: cannot create certificate signing request: Post "https://external-control-plane:6443/apis/certificates.k8s.io/v1/certificatesigningrequests": dial tcp 172.18.0.4:6443: connect: connection refused
Aug 17 17:50:27 external-control-plane kubelet[304]: W0817 17:50:27.083015     304 sysinfo.go:203] Nodes topology is not available, providing CPU topology
Aug 17 17:50:27 external-control-plane kubelet[304]: I0817 17:50:27.087726     304 container_manager_linux.go:278] "Container manager verified user specified cgroup-root exists" cgroupRoot=[kubelet]
Aug 17 17:50:27 external-control-plane kubelet[304]: I0817 17:50:27.087788     304 container_manager_linux.go:283] "Creating Container Manager object based on Node Config" nodeConfig={RuntimeCgroupsName: SystemCgroupsName: KubeletCgroupsName: ContainerRuntime:remote CgroupsPerQOS:true CgroupRoot:/kubelet CgroupDriver:cgroupfs KubeletRootDir:/var/lib/kubelet ProtectKernelDefaults:false NodeAllocatableConfig:{KubeReservedCgroupName: SystemReservedCgroupName: ReservedSystemCPUs: EnforceNodeAllocatable:map[pods:{}] KubeReserved:map[] SystemReserved:map[] HardEvictionThresholds:[]} QOSReserved:map[] ExperimentalCPUManagerPolicy:none ExperimentalTopologyManagerScope:container ExperimentalCPUManagerReconcilePeriod:10s ExperimentalMemoryManagerPolicy:None ExperimentalMemoryManagerReservedMemory:[] ExperimentalPodPidsLimit:-1 EnforceCPULimits:true CPUCFSQuotaPeriod:100ms ExperimentalTopologyManagerPolicy:none}
Aug 17 17:50:27 external-control-plane kubelet[304]: I0817 17:50:27.087897     304 topology_manager.go:120] "Creating topology manager with policy per scope" topologyPolicyName="none" topologyScopeName="container"
Aug 17 17:50:27 external-control-plane kubelet[304]: I0817 17:50:27.087921     304 container_manager_linux.go:314] "Initializing Topology Manager" policy="none" scope="container"
Aug 17 17:50:27 external-control-plane kubelet[304]: I0817 17:50:27.087936     304 container_manager_linux.go:319] "Creating device plugin manager" devicePluginEnabled=true
Aug 17 17:50:27 external-control-plane kubelet[304]: I0817 17:50:27.088135     304 remote_runtime.go:62] parsed scheme: ""
Aug 17 17:50:27 external-control-plane kubelet[304]: I0817 17:50:27.088155     304 remote_runtime.go:62] scheme "" not registered, fallback to default scheme
Aug 17 17:50:27 external-control-plane kubelet[304]: I0817 17:50:27.088193     304 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{/run/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}
Aug 17 17:50:27 external-control-plane kubelet[304]: I0817 17:50:27.088213     304 clientconn.go:948] ClientConn switching balancer to "pick_first"
Aug 17 17:50:27 external-control-plane kubelet[304]: I0817 17:50:27.088309     304 remote_image.go:50] parsed scheme: ""
Aug 17 17:50:27 external-control-plane kubelet[304]: I0817 17:50:27.088324     304 remote_image.go:50] scheme "" not registered, fallback to default scheme
Aug 17 17:50:27 external-control-plane kubelet[304]: I0817 17:50:27.088341     304 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{/run/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}
Aug 17 17:50:27 external-control-plane kubelet[304]: I0817 17:50:27.088357     304 clientconn.go:948] ClientConn switching balancer to "pick_first"
Aug 17 17:50:27 external-control-plane kubelet[304]: I0817 17:50:27.088428     304 kubelet.go:404] "Attempting to sync node with API server"
Aug 17 17:50:27 external-control-plane kubelet[304]: I0817 17:50:27.088454     304 kubelet.go:272] "Adding static pod path" path="/etc/kubernetes/manifests"
Aug 17 17:50:27 external-control-plane kubelet[304]: I0817 17:50:27.088850     304 kubelet.go:283] "Adding apiserver pod source"
Aug 17 17:50:27 external-control-plane kubelet[304]: I0817 17:50:27.088876     304 apiserver.go:42] "Waiting for node sync before watching apiserver pods"
Aug 17 17:50:27 external-control-plane kubelet[304]: E0817 17:50:27.090623     304 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Service: failed to list *v1.Service: Get "https://external-control-plane:6443/api/v1/services?limit=500&resourceVersion=0": dial tcp 172.18.0.4:6443: connect: connection refused
Aug 17 17:50:27 external-control-plane kubelet[304]: E0817 17:50:27.090668     304 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Node: failed to list *v1.Node: Get "https://external-control-plane:6443/api/v1/nodes?fieldSelector=metadata.name%3Dexternal-control-plane&limit=500&resourceVersion=0": dial tcp 172.18.0.4:6443: connect: connection refused
Aug 17 17:50:27 external-control-plane kubelet[304]: I0817 17:50:27.092844     304 kuberuntime_manager.go:222] "Container runtime initialized" containerRuntime="containerd" version="v1.5.1" apiVersion="v1alpha2"
Aug 17 17:50:28 external-control-plane kubelet[304]: E0817 17:50:28.002475     304 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Service: failed to list *v1.Service: Get "https://external-control-plane:6443/api/v1/services?limit=500&resourceVersion=0": dial tcp 172.18.0.4:6443: connect: connection refused
Aug 17 17:50:28 external-control-plane kubelet[304]: E0817 17:50:28.128250     304 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Node: failed to list *v1.Node: Get "https://external-control-plane:6443/api/v1/nodes?fieldSelector=metadata.name%3Dexternal-control-plane&limit=500&resourceVersion=0": dial tcp 172.18.0.4:6443: connect: connection refused
Aug 17 17:50:28 external-control-plane kubelet[304]: E0817 17:50:28.170779     304 certificate_manager.go:437] Failed while requesting a signed certificate from the master: cannot create certificate signing request: Post "https://external-control-plane:6443/apis/certificates.k8s.io/v1/certificatesigningrequests": dial tcp 172.18.0.4:6443: connect: connection refused
Aug 17 17:50:29 external-control-plane kubelet[304]: E0817 17:50:29.752881     304 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Node: failed to list *v1.Node: Get "https://external-control-plane:6443/api/v1/nodes?fieldSelector=metadata.name%3Dexternal-control-plane&limit=500&resourceVersion=0": dial tcp 172.18.0.4:6443: connect: connection refused
Aug 17 17:50:30 external-control-plane kubelet[304]: E0817 17:50:30.365768     304 aws_credentials.go:77] while getting AWS credentials NoCredentialProviders: no valid providers in chain. Deprecated.
Aug 17 17:50:30 external-control-plane kubelet[304]:         For verbose messaging see aws.Config.CredentialsChainVerboseErrors
Aug 17 17:50:30 external-control-plane kubelet[304]: W0817 17:50:30.365988     304 probe.go:268] Flexvolume plugin directory at /usr/libexec/kubernetes/kubelet-plugins/volume/exec/ does not exist. Recreating.
Aug 17 17:50:30 external-control-plane kubelet[304]: I0817 17:50:30.366475     304 server.go:1190] "Started kubelet"
Aug 17 17:50:30 external-control-plane kubelet[304]: I0817 17:50:30.366571     304 server.go:149] "Starting to listen" address="0.0.0.0" port=10250
Aug 17 17:50:30 external-control-plane kubelet[304]: I0817 17:50:30.368085     304 server.go:405] "Adding debug handlers to kubelet server"
Aug 17 17:50:30 external-control-plane kubelet[304]: E0817 17:50:30.367621     304 event.go:273] Unable to write event: '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"external-control-plane.169c2959af050e94", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"external-control-plane", UID:"external-control-plane", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"Starting", Message:"Starting kubelet.", Source:v1.EventSource{Component:"kubelet", Host:"external-control-plane"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xc03f1b9995d79294, ext:9039773501, loc:(*time.Location)(0x74aba00)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xc03f1b9995d79294, ext:9039773501, loc:(*time.Location)(0x74aba00)}}, Count:1, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'Post "https://external-control-plane:6443/api/v1/namespaces/default/events": dial tcp 172.18.0.4:6443: connect: connection refused'(may retry after sleeping)
Aug 17 17:50:30 external-control-plane kubelet[304]: I0817 17:50:30.368809     304 fs_resource_analyzer.go:67] "Starting FS ResourceAnalyzer"
Aug 17 17:50:30 external-control-plane kubelet[304]: I0817 17:50:30.369025     304 volume_manager.go:271] "Starting Kubelet Volume Manager"
Aug 17 17:50:30 external-control-plane kubelet[304]: I0817 17:50:30.369097     304 desired_state_of_world_populator.go:141] "Desired state populator starts to run"
Aug 17 17:50:30 external-control-plane kubelet[304]: E0817 17:50:30.369654     304 controller.go:144] failed to ensure lease exists, will retry in 200ms, error: Get "https://external-control-plane:6443/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/external-control-plane?timeout=10s": dial tcp 172.18.0.4:6443: connect: connection refused
Aug 17 17:50:30 external-control-plane kubelet[304]: E0817 17:50:30.369879     304 kubelet.go:2211] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized"
Aug 17 17:50:30 external-control-plane kubelet[304]: I0817 17:50:30.370275     304 client.go:86] parsed scheme: "unix"
Aug 17 17:50:30 external-control-plane kubelet[304]: I0817 17:50:30.370305     304 client.go:86] scheme "unix" not registered, fallback to default scheme
Aug 17 17:50:30 external-control-plane kubelet[304]: E0817 17:50:30.370992     304 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.CSIDriver: failed to list *v1.CSIDriver: Get "https://external-control-plane:6443/apis/storage.k8s.io/v1/csidrivers?limit=500&resourceVersion=0": dial tcp 172.18.0.4:6443: connect: connection refused
Aug 17 17:50:30 external-control-plane kubelet[304]: I0817 17:50:30.371889     304 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}
Aug 17 17:50:30 external-control-plane kubelet[304]: I0817 17:50:30.371929     304 clientconn.go:948] ClientConn switching balancer to "pick_first"
Aug 17 17:50:30 external-control-plane kubelet[304]: I0817 17:50:30.414111     304 cpu_manager.go:199] "Starting CPU manager" policy="none"
Aug 17 17:50:30 external-control-plane kubelet[304]: I0817 17:50:30.414152     304 cpu_manager.go:200] "Reconciling" reconcilePeriod="10s"
Aug 17 17:50:30 external-control-plane kubelet[304]: I0817 17:50:30.414248     304 state_mem.go:36] "Initialized new in-memory state store"
Aug 17 17:50:30 external-control-plane kubelet[304]: I0817 17:50:30.416449     304 policy_none.go:44] "None policy: Start"
Aug 17 17:50:30 external-control-plane kubelet[304]: I0817 17:50:30.427186     304 manager.go:600] "Failed to retrieve checkpoint" checkpoint="kubelet_internal_checkpoint" err="checkpoint is not found"
Aug 17 17:50:30 external-control-plane kubelet[304]: I0817 17:50:30.427562     304 plugin_manager.go:114] "Starting Kubelet Plugin Manager"
Aug 17 17:50:30 external-control-plane kubelet[304]: E0817 17:50:30.428821     304 eviction_manager.go:255] "Eviction manager: failed to get summary stats" err="failed to get node info: node \"external-control-plane\" not found"
Aug 17 17:50:30 external-control-plane kubelet[304]: E0817 17:50:30.469787     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:30 external-control-plane kubelet[304]: I0817 17:50:30.471165     304 kubelet_node_status.go:71] "Attempting to register node" node="external-control-plane"
Aug 17 17:50:30 external-control-plane kubelet[304]: E0817 17:50:30.471927     304 kubelet_node_status.go:93] "Unable to register node with API server" err="Post \"https://external-control-plane:6443/api/v1/nodes\": dial tcp 172.18.0.4:6443: connect: connection refused" node="external-control-plane"
Aug 17 17:50:30 external-control-plane kubelet[304]: E0817 17:50:30.569909     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:30 external-control-plane kubelet[304]: E0817 17:50:30.570721     304 controller.go:144] failed to ensure lease exists, will retry in 400ms, error: Get "https://external-control-plane:6443/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/external-control-plane?timeout=10s": dial tcp 172.18.0.4:6443: connect: connection refused
Aug 17 17:50:30 external-control-plane kubelet[304]: E0817 17:50:30.670918     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:30 external-control-plane kubelet[304]: I0817 17:50:30.673313     304 kubelet_node_status.go:71] "Attempting to register node" node="external-control-plane"
Aug 17 17:50:30 external-control-plane kubelet[304]: E0817 17:50:30.674231     304 kubelet_node_status.go:93] "Unable to register node with API server" err="Post \"https://external-control-plane:6443/api/v1/nodes\": dial tcp 172.18.0.4:6443: connect: connection refused" node="external-control-plane"
Aug 17 17:50:30 external-control-plane kubelet[304]: E0817 17:50:30.751967     304 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Service: failed to list *v1.Service: Get "https://external-control-plane:6443/api/v1/services?limit=500&resourceVersion=0": dial tcp 172.18.0.4:6443: connect: connection refused
Aug 17 17:50:30 external-control-plane kubelet[304]: E0817 17:50:30.772182     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:30 external-control-plane kubelet[304]: I0817 17:50:30.800375     304 kubelet_network_linux.go:56] "Initialized protocol iptables rules." protocol=IPv4
Aug 17 17:50:30 external-control-plane kubelet[304]: E0817 17:50:30.873032     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:30 external-control-plane kubelet[304]: E0817 17:50:30.972652     304 controller.go:144] failed to ensure lease exists, will retry in 800ms, error: Get "https://external-control-plane:6443/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/external-control-plane?timeout=10s": dial tcp 172.18.0.4:6443: connect: connection refused
Aug 17 17:50:30 external-control-plane kubelet[304]: E0817 17:50:30.973354     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:31 external-control-plane kubelet[304]: I0817 17:50:31.032598     304 kubelet_network_linux.go:56] "Initialized protocol iptables rules." protocol=IPv6
Aug 17 17:50:31 external-control-plane kubelet[304]: I0817 17:50:31.032963     304 status_manager.go:157] "Starting to sync pod status with apiserver"
Aug 17 17:50:31 external-control-plane kubelet[304]: I0817 17:50:31.033010     304 kubelet.go:1846] "Starting kubelet main sync loop"
Aug 17 17:50:31 external-control-plane kubelet[304]: E0817 17:50:31.033176     304 kubelet.go:1870] "Skipping pod synchronization" err="PLEG is not healthy: pleg has yet to be successful"
Aug 17 17:50:31 external-control-plane kubelet[304]: E0817 17:50:31.035551     304 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.RuntimeClass: failed to list *v1.RuntimeClass: Get "https://external-control-plane:6443/apis/node.k8s.io/v1/runtimeclasses?limit=500&resourceVersion=0": dial tcp 172.18.0.4:6443: connect: connection refused
Aug 17 17:50:31 external-control-plane kubelet[304]: E0817 17:50:31.074312     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:31 external-control-plane kubelet[304]: I0817 17:50:31.080446     304 kubelet_node_status.go:71] "Attempting to register node" node="external-control-plane"
Aug 17 17:50:31 external-control-plane kubelet[304]: I0817 17:50:31.137189     304 topology_manager.go:187] "Topology Admit Handler"
Aug 17 17:50:31 external-control-plane kubelet[304]: I0817 17:50:31.138700     304 topology_manager.go:187] "Topology Admit Handler"
Aug 17 17:50:31 external-control-plane kubelet[304]: I0817 17:50:31.139877     304 topology_manager.go:187] "Topology Admit Handler"
Aug 17 17:50:31 external-control-plane kubelet[304]: I0817 17:50:31.141020     304 topology_manager.go:187] "Topology Admit Handler"
Aug 17 17:50:31 external-control-plane kubelet[304]: I0817 17:50:31.142507     304 status_manager.go:566] "Failed to get status for pod" podUID=ce54e720217c6f6d55666abfec72a7cc pod="kube-system/etcd-external-control-plane" error="Get \"https://external-control-plane:6443/api/v1/namespaces/kube-system/pods/etcd-external-control-plane\": dial tcp 172.18.0.4:6443: connect: connection refused"
Aug 17 17:50:31 external-control-plane kubelet[304]: I0817 17:50:31.143018     304 status_manager.go:566] "Failed to get status for pod" podUID=949099c6581d332a8f1dbcdbd524d0ae pod="kube-system/kube-apiserver-external-control-plane" error="Get \"https://external-control-plane:6443/api/v1/namespaces/kube-system/pods/kube-apiserver-external-control-plane\": dial tcp 172.18.0.4:6443: connect: connection refused"
Aug 17 17:50:31 external-control-plane kubelet[304]: I0817 17:50:31.144626     304 status_manager.go:566] "Failed to get status for pod" podUID=62d94253dfb3bc7efea906594d5c451f pod="kube-system/kube-controller-manager-external-control-plane" error="Get \"https://external-control-plane:6443/api/v1/namespaces/kube-system/pods/kube-controller-manager-external-control-plane\": dial tcp 172.18.0.4:6443: connect: connection refused"
Aug 17 17:50:31 external-control-plane kubelet[304]: I0817 17:50:31.147281     304 status_manager.go:566] "Failed to get status for pod" podUID=2684a87c49138cdc77a25350f55b72ff pod="kube-system/kube-scheduler-external-control-plane" error="Get \"https://external-control-plane:6443/api/v1/namespaces/kube-system/pods/kube-scheduler-external-control-plane\": dial tcp 172.18.0.4:6443: connect: connection refused"
Aug 17 17:50:31 external-control-plane kubelet[304]: W0817 17:50:31.147305     304 container.go:586] Failed to update stats for container "/kubelet/kubepods/burstable/podce54e720217c6f6d55666abfec72a7cc": /sys/fs/cgroup/cpuset/kubelet/kubepods/burstable/podce54e720217c6f6d55666abfec72a7cc/cpuset.mems found to be empty, continuing to push stats
Aug 17 17:50:31 external-control-plane kubelet[304]: E0817 17:50:31.152553     304 kubelet_node_status.go:93] "Unable to register node with API server" err="Post \"https://external-control-plane:6443/api/v1/nodes\": dial tcp 172.18.0.4:6443: connect: connection refused" node="external-control-plane"
Aug 17 17:50:31 external-control-plane kubelet[304]: E0817 17:50:31.174973     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:31 external-control-plane kubelet[304]: I0817 17:50:31.174978     304 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"usr-local-share-ca-certificates\" (UniqueName: \"kubernetes.io/host-path/949099c6581d332a8f1dbcdbd524d0ae-usr-local-share-ca-certificates\") pod \"kube-apiserver-external-control-plane\" (UID: \"949099c6581d332a8f1dbcdbd524d0ae\") "
Aug 17 17:50:31 external-control-plane kubelet[304]: I0817 17:50:31.175130     304 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"usr-share-ca-certificates\" (UniqueName: \"kubernetes.io/host-path/949099c6581d332a8f1dbcdbd524d0ae-usr-share-ca-certificates\") pod \"kube-apiserver-external-control-plane\" (UID: \"949099c6581d332a8f1dbcdbd524d0ae\") "
Aug 17 17:50:31 external-control-plane kubelet[304]: I0817 17:50:31.175174     304 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"k8s-certs\" (UniqueName: \"kubernetes.io/host-path/62d94253dfb3bc7efea906594d5c451f-k8s-certs\") pod \"kube-controller-manager-external-control-plane\" (UID: \"62d94253dfb3bc7efea906594d5c451f\") "
Aug 17 17:50:31 external-control-plane kubelet[304]: I0817 17:50:31.175216     304 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"kubeconfig\" (UniqueName: \"kubernetes.io/host-path/62d94253dfb3bc7efea906594d5c451f-kubeconfig\") pod \"kube-controller-manager-external-control-plane\" (UID: \"62d94253dfb3bc7efea906594d5c451f\") "
Aug 17 17:50:31 external-control-plane kubelet[304]: I0817 17:50:31.175255     304 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"usr-local-share-ca-certificates\" (UniqueName: \"kubernetes.io/host-path/62d94253dfb3bc7efea906594d5c451f-usr-local-share-ca-certificates\") pod \"kube-controller-manager-external-control-plane\" (UID: \"62d94253dfb3bc7efea906594d5c451f\") "
Aug 17 17:50:31 external-control-plane kubelet[304]: I0817 17:50:31.175295     304 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"etcd-certs\" (UniqueName: \"kubernetes.io/host-path/ce54e720217c6f6d55666abfec72a7cc-etcd-certs\") pod \"etcd-external-control-plane\" (UID: \"ce54e720217c6f6d55666abfec72a7cc\") "
Aug 17 17:50:31 external-control-plane kubelet[304]: I0817 17:50:31.175335     304 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"usr-share-ca-certificates\" (UniqueName: \"kubernetes.io/host-path/62d94253dfb3bc7efea906594d5c451f-usr-share-ca-certificates\") pod \"kube-controller-manager-external-control-plane\" (UID: \"62d94253dfb3bc7efea906594d5c451f\") "
Aug 17 17:50:31 external-control-plane kubelet[304]: I0817 17:50:31.175371     304 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"etcd-data\" (UniqueName: \"kubernetes.io/host-path/ce54e720217c6f6d55666abfec72a7cc-etcd-data\") pod \"etcd-external-control-plane\" (UID: \"ce54e720217c6f6d55666abfec72a7cc\") "
Aug 17 17:50:31 external-control-plane kubelet[304]: I0817 17:50:31.175456     304 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"ca-certs\" (UniqueName: \"kubernetes.io/host-path/949099c6581d332a8f1dbcdbd524d0ae-ca-certs\") pod \"kube-apiserver-external-control-plane\" (UID: \"949099c6581d332a8f1dbcdbd524d0ae\") "
Aug 17 17:50:31 external-control-plane kubelet[304]: I0817 17:50:31.175498     304 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"etc-ca-certificates\" (UniqueName: \"kubernetes.io/host-path/949099c6581d332a8f1dbcdbd524d0ae-etc-ca-certificates\") pod \"kube-apiserver-external-control-plane\" (UID: \"949099c6581d332a8f1dbcdbd524d0ae\") "
Aug 17 17:50:31 external-control-plane kubelet[304]: I0817 17:50:31.175533     304 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"k8s-certs\" (UniqueName: \"kubernetes.io/host-path/949099c6581d332a8f1dbcdbd524d0ae-k8s-certs\") pod \"kube-apiserver-external-control-plane\" (UID: \"949099c6581d332a8f1dbcdbd524d0ae\") "
Aug 17 17:50:31 external-control-plane kubelet[304]: I0817 17:50:31.175571     304 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"ca-certs\" (UniqueName: \"kubernetes.io/host-path/62d94253dfb3bc7efea906594d5c451f-ca-certs\") pod \"kube-controller-manager-external-control-plane\" (UID: \"62d94253dfb3bc7efea906594d5c451f\") "
Aug 17 17:50:31 external-control-plane kubelet[304]: I0817 17:50:31.175603     304 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"kubeconfig\" (UniqueName: \"kubernetes.io/host-path/2684a87c49138cdc77a25350f55b72ff-kubeconfig\") pod \"kube-scheduler-external-control-plane\" (UID: \"2684a87c49138cdc77a25350f55b72ff\") "
Aug 17 17:50:31 external-control-plane kubelet[304]: I0817 17:50:31.175637     304 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"etc-ca-certificates\" (UniqueName: \"kubernetes.io/host-path/62d94253dfb3bc7efea906594d5c451f-etc-ca-certificates\") pod \"kube-controller-manager-external-control-plane\" (UID: \"62d94253dfb3bc7efea906594d5c451f\") "
Aug 17 17:50:31 external-control-plane kubelet[304]: I0817 17:50:31.175694     304 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"flexvolume-dir\" (UniqueName: \"kubernetes.io/host-path/62d94253dfb3bc7efea906594d5c451f-flexvolume-dir\") pod \"kube-controller-manager-external-control-plane\" (UID: \"62d94253dfb3bc7efea906594d5c451f\") "
Aug 17 17:50:31 external-control-plane kubelet[304]: E0817 17:50:31.275591     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:31 external-control-plane kubelet[304]: E0817 17:50:31.376742     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:31 external-control-plane kubelet[304]: E0817 17:50:31.476921     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:31 external-control-plane kubelet[304]: E0817 17:50:31.577155     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:31 external-control-plane kubelet[304]: E0817 17:50:31.678318     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:31 external-control-plane kubelet[304]: E0817 17:50:31.774197     304 controller.go:144] failed to ensure lease exists, will retry in 1.6s, error: Get "https://external-control-plane:6443/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/external-control-plane?timeout=10s": dial tcp 172.18.0.4:6443: connect: connection refused
Aug 17 17:50:31 external-control-plane kubelet[304]: E0817 17:50:31.778490     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:31 external-control-plane kubelet[304]: E0817 17:50:31.846187     304 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.CSIDriver: failed to list *v1.CSIDriver: Get "https://external-control-plane:6443/apis/storage.k8s.io/v1/csidrivers?limit=500&resourceVersion=0": dial tcp 172.18.0.4:6443: connect: connection refused
Aug 17 17:50:31 external-control-plane kubelet[304]: E0817 17:50:31.880485     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:31 external-control-plane kubelet[304]: I0817 17:50:31.961483     304 kubelet_node_status.go:71] "Attempting to register node" node="external-control-plane"
Aug 17 17:50:31 external-control-plane kubelet[304]: E0817 17:50:31.962452     304 kubelet_node_status.go:93] "Unable to register node with API server" err="Post \"https://external-control-plane:6443/api/v1/nodes\": dial tcp 172.18.0.4:6443: connect: connection refused" node="external-control-plane"
Aug 17 17:50:31 external-control-plane kubelet[304]: E0817 17:50:31.981231     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:32 external-control-plane kubelet[304]: E0817 17:50:32.082160     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:32 external-control-plane kubelet[304]: E0817 17:50:32.085324     304 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.RuntimeClass: failed to list *v1.RuntimeClass: Get "https://external-control-plane:6443/apis/node.k8s.io/v1/runtimeclasses?limit=500&resourceVersion=0": dial tcp 172.18.0.4:6443: connect: connection refused
Aug 17 17:50:32 external-control-plane kubelet[304]: E0817 17:50:32.184428     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:32 external-control-plane kubelet[304]: E0817 17:50:32.293535     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:32 external-control-plane kubelet[304]: E0817 17:50:32.400167     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:32 external-control-plane kubelet[304]: E0817 17:50:32.500988     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:32 external-control-plane kubelet[304]: E0817 17:50:32.611387     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:32 external-control-plane kubelet[304]: E0817 17:50:32.711469     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:32 external-control-plane kubelet[304]: E0817 17:50:32.811877     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:32 external-control-plane kubelet[304]: E0817 17:50:32.912910     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:33 external-control-plane kubelet[304]: E0817 17:50:33.013881     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:33 external-control-plane kubelet[304]: E0817 17:50:33.114660     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:33 external-control-plane kubelet[304]: E0817 17:50:33.198993     304 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Node: failed to list *v1.Node: Get "https://external-control-plane:6443/api/v1/nodes?fieldSelector=metadata.name%3Dexternal-control-plane&limit=500&resourceVersion=0": dial tcp 172.18.0.4:6443: connect: connection refused
Aug 17 17:50:33 external-control-plane kubelet[304]: E0817 17:50:33.215158     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:33 external-control-plane kubelet[304]: E0817 17:50:33.316239     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:33 external-control-plane kubelet[304]: E0817 17:50:33.375640     304 controller.go:144] failed to ensure lease exists, will retry in 3.2s, error: Get "https://external-control-plane:6443/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/external-control-plane?timeout=10s": dial tcp 172.18.0.4:6443: connect: connection refused
Aug 17 17:50:33 external-control-plane kubelet[304]: E0817 17:50:33.416675     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:33 external-control-plane kubelet[304]: E0817 17:50:33.434367     304 event.go:273] Unable to write event: '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"external-control-plane.169c2959af050e94", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"external-control-plane", UID:"external-control-plane", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"Starting", Message:"Starting kubelet.", Source:v1.EventSource{Component:"kubelet", Host:"external-control-plane"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xc03f1b9995d79294, ext:9039773501, loc:(*time.Location)(0x74aba00)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xc03f1b9995d79294, ext:9039773501, loc:(*time.Location)(0x74aba00)}}, Count:1, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'Post "https://external-control-plane:6443/api/v1/namespaces/default/events": dial tcp 172.18.0.4:6443: connect: connection refused'(may retry after sleeping)
Aug 17 17:50:33 external-control-plane kubelet[304]: E0817 17:50:33.517635     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:33 external-control-plane kubelet[304]: I0817 17:50:33.564491     304 kubelet_node_status.go:71] "Attempting to register node" node="external-control-plane"
Aug 17 17:50:33 external-control-plane kubelet[304]: E0817 17:50:33.565235     304 kubelet_node_status.go:93] "Unable to register node with API server" err="Post \"https://external-control-plane:6443/api/v1/nodes\": dial tcp 172.18.0.4:6443: connect: connection refused" node="external-control-plane"
Aug 17 17:50:33 external-control-plane kubelet[304]: E0817 17:50:33.617847     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:33 external-control-plane kubelet[304]: E0817 17:50:33.718980     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:33 external-control-plane kubelet[304]: E0817 17:50:33.819918     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:33 external-control-plane kubelet[304]: E0817 17:50:33.915613     304 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.CSIDriver: failed to list *v1.CSIDriver: Get "https://external-control-plane:6443/apis/storage.k8s.io/v1/csidrivers?limit=500&resourceVersion=0": dial tcp 172.18.0.4:6443: connect: connection refused
Aug 17 17:50:33 external-control-plane kubelet[304]: E0817 17:50:33.921096     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:34 external-control-plane kubelet[304]: E0817 17:50:34.021696     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:34 external-control-plane kubelet[304]: E0817 17:50:34.122228     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:34 external-control-plane kubelet[304]: E0817 17:50:34.222653     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:34 external-control-plane kubelet[304]: E0817 17:50:34.322811     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:34 external-control-plane kubelet[304]: E0817 17:50:34.423411     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:34 external-control-plane kubelet[304]: E0817 17:50:34.523811     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:34 external-control-plane kubelet[304]: E0817 17:50:34.625130     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:34 external-control-plane kubelet[304]: E0817 17:50:34.725688     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:34 external-control-plane kubelet[304]: E0817 17:50:34.826513     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:34 external-control-plane kubelet[304]: E0817 17:50:34.927658     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:35 external-control-plane kubelet[304]: E0817 17:50:35.028764     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:35 external-control-plane kubelet[304]: E0817 17:50:35.129827     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:35 external-control-plane kubelet[304]: E0817 17:50:35.230980     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:35 external-control-plane kubelet[304]: E0817 17:50:35.331622     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:35 external-control-plane kubelet[304]: E0817 17:50:35.429513     304 kubelet.go:2211] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized"
Aug 17 17:50:35 external-control-plane kubelet[304]: E0817 17:50:35.432671     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:35 external-control-plane kubelet[304]: E0817 17:50:35.533171     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:35 external-control-plane kubelet[304]: E0817 17:50:35.633650     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:35 external-control-plane kubelet[304]: E0817 17:50:35.734757     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:35 external-control-plane kubelet[304]: E0817 17:50:35.835756     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:35 external-control-plane kubelet[304]: E0817 17:50:35.936935     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:36 external-control-plane kubelet[304]: E0817 17:50:36.037564     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:36 external-control-plane kubelet[304]: E0817 17:50:36.138263     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:36 external-control-plane kubelet[304]: E0817 17:50:36.238808     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:36 external-control-plane kubelet[304]: E0817 17:50:36.338992     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:36 external-control-plane kubelet[304]: E0817 17:50:36.440157     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:36 external-control-plane kubelet[304]: E0817 17:50:36.540377     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:36 external-control-plane kubelet[304]: E0817 17:50:36.641510     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:36 external-control-plane kubelet[304]: E0817 17:50:36.741651     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:36 external-control-plane kubelet[304]: I0817 17:50:36.767278     304 kubelet_node_status.go:71] "Attempting to register node" node="external-control-plane"
Aug 17 17:50:36 external-control-plane kubelet[304]: E0817 17:50:36.841955     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:36 external-control-plane kubelet[304]: E0817 17:50:36.943180     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:37 external-control-plane kubelet[304]: E0817 17:50:37.044313     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:37 external-control-plane kubelet[304]: E0817 17:50:37.145176     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:37 external-control-plane kubelet[304]: E0817 17:50:37.245611     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:37 external-control-plane kubelet[304]: E0817 17:50:37.346686     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:37 external-control-plane kubelet[304]: E0817 17:50:37.446835     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:37 external-control-plane kubelet[304]: E0817 17:50:37.547822     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:37 external-control-plane kubelet[304]: E0817 17:50:37.648963     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:37 external-control-plane kubelet[304]: E0817 17:50:37.749467     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:37 external-control-plane kubelet[304]: E0817 17:50:37.849664     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:37 external-control-plane kubelet[304]: E0817 17:50:37.950723     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:38 external-control-plane kubelet[304]: E0817 17:50:38.051670     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:38 external-control-plane kubelet[304]: E0817 17:50:38.152324     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:38 external-control-plane kubelet[304]: E0817 17:50:38.253496     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:38 external-control-plane kubelet[304]: E0817 17:50:38.354715     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:38 external-control-plane kubelet[304]: E0817 17:50:38.455266     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:38 external-control-plane kubelet[304]: E0817 17:50:38.556549     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:38 external-control-plane kubelet[304]: E0817 17:50:38.656973     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:38 external-control-plane kubelet[304]: E0817 17:50:38.757128     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:38 external-control-plane kubelet[304]: E0817 17:50:38.857249     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:38 external-control-plane kubelet[304]: E0817 17:50:38.957488     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:39 external-control-plane kubelet[304]: E0817 17:50:39.058696     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:39 external-control-plane kubelet[304]: E0817 17:50:39.159473     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:39 external-control-plane kubelet[304]: E0817 17:50:39.260500     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:39 external-control-plane kubelet[304]: E0817 17:50:39.361578     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:39 external-control-plane kubelet[304]: E0817 17:50:39.461773     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:39 external-control-plane kubelet[304]: E0817 17:50:39.561920     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:39 external-control-plane kubelet[304]: E0817 17:50:39.662237     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:39 external-control-plane kubelet[304]: E0817 17:50:39.762541     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:39 external-control-plane kubelet[304]: E0817 17:50:39.863173     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:39 external-control-plane kubelet[304]: E0817 17:50:39.964251     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:40 external-control-plane kubelet[304]: E0817 17:50:40.065366     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:40 external-control-plane kubelet[304]: E0817 17:50:40.166665     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:40 external-control-plane kubelet[304]: E0817 17:50:40.267468     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:40 external-control-plane kubelet[304]: E0817 17:50:40.368307     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:40 external-control-plane kubelet[304]: E0817 17:50:40.429362     304 eviction_manager.go:255] "Eviction manager: failed to get summary stats" err="failed to get node info: node \"external-control-plane\" not found"
Aug 17 17:50:40 external-control-plane kubelet[304]: E0817 17:50:40.430652     304 kubelet.go:2211] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized"
Aug 17 17:50:40 external-control-plane kubelet[304]: E0817 17:50:40.469626     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:40 external-control-plane kubelet[304]: E0817 17:50:40.570666     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:40 external-control-plane kubelet[304]: E0817 17:50:40.671048     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:40 external-control-plane kubelet[304]: E0817 17:50:40.673204     304 nodelease.go:49] "Failed to get node when trying to set owner ref to the node lease" err="nodes \"external-control-plane\" not found" node="external-control-plane"
Aug 17 17:50:40 external-control-plane kubelet[304]: E0817 17:50:40.772149     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:40 external-control-plane kubelet[304]: I0817 17:50:40.787032     304 kubelet_node_status.go:74] "Successfully registered node" node="external-control-plane"
Aug 17 17:50:40 external-control-plane kubelet[304]: E0817 17:50:40.872886     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:40 external-control-plane kubelet[304]: E0817 17:50:40.973895     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:41 external-control-plane kubelet[304]: E0817 17:50:41.074872     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:41 external-control-plane kubelet[304]: E0817 17:50:41.175347     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:41 external-control-plane kubelet[304]: E0817 17:50:41.275637     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:41 external-control-plane kubelet[304]: E0817 17:50:41.376492     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:41 external-control-plane kubelet[304]: E0817 17:50:41.477721     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:41 external-control-plane kubelet[304]: E0817 17:50:41.579191     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:41 external-control-plane kubelet[304]: E0817 17:50:41.680199     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:41 external-control-plane kubelet[304]: E0817 17:50:41.781389     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:41 external-control-plane kubelet[304]: E0817 17:50:41.882448     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:41 external-control-plane kubelet[304]: E0817 17:50:41.982590     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:42 external-control-plane kubelet[304]: E0817 17:50:42.083607     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:42 external-control-plane kubelet[304]: E0817 17:50:42.184524     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:42 external-control-plane kubelet[304]: E0817 17:50:42.284712     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:42 external-control-plane kubelet[304]: E0817 17:50:42.385599     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:42 external-control-plane kubelet[304]: E0817 17:50:42.486261     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:42 external-control-plane kubelet[304]: E0817 17:50:42.587144     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:42 external-control-plane kubelet[304]: E0817 17:50:42.688174     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:42 external-control-plane kubelet[304]: E0817 17:50:42.789297     304 kubelet.go:2291] "Error getting node" err="node \"external-control-plane\" not found"
Aug 17 17:50:43 external-control-plane kubelet[304]: I0817 17:50:43.065768     304 apiserver.go:52] "Watching apiserver"
Aug 17 17:50:43 external-control-plane kubelet[304]: I0817 17:50:43.141640     304 reconciler.go:157] "Reconciler: start to sync state"
Aug 17 17:50:43 external-control-plane systemd[1]: Stopping kubelet: The Kubernetes Node Agent...
Aug 17 17:50:43 external-control-plane kubelet[304]: I0817 17:50:43.977613     304 dynamic_cafile_content.go:182] Shutting down client-ca-bundle::/etc/kubernetes/pki/ca.crt
Aug 17 17:50:44 external-control-plane systemd[1]: kubelet.service: Succeeded.
Aug 17 17:50:44 external-control-plane systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
Aug 17 17:50:44 external-control-plane systemd[1]: Starting kubelet: The Kubernetes Node Agent...
Aug 17 17:50:44 external-control-plane systemd[1]: Started kubelet: The Kubernetes Node Agent.
Aug 17 17:50:44 external-control-plane kubelet[783]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Aug 17 17:50:44 external-control-plane kubelet[783]: Flag --provider-id has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Aug 17 17:50:44 external-control-plane kubelet[783]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Aug 17 17:50:44 external-control-plane kubelet[783]: Flag --cgroup-root has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Aug 17 17:50:44 external-control-plane kubelet[783]: I0817 17:50:44.134026     783 server.go:197] "Warning: For remote container runtime, --pod-infra-container-image is ignored in kubelet, which should be set in that remote runtime instead"
Aug 17 17:50:44 external-control-plane kubelet[783]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Aug 17 17:50:44 external-control-plane kubelet[783]: Flag --provider-id has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Aug 17 17:50:44 external-control-plane kubelet[783]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Aug 17 17:50:44 external-control-plane kubelet[783]: Flag --cgroup-root has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Aug 17 17:50:44 external-control-plane kubelet[783]: I0817 17:50:44.153448     783 server.go:440] "Kubelet version" kubeletVersion="v1.21.1"
Aug 17 17:50:44 external-control-plane kubelet[783]: I0817 17:50:44.153877     783 server.go:851] "Client rotation is on, will bootstrap in background"
Aug 17 17:50:44 external-control-plane kubelet[783]: I0817 17:50:44.156401     783 certificate_store.go:130] Loading cert/key pair from "/var/lib/kubelet/pki/kubelet-client-current.pem".
Aug 17 17:50:44 external-control-plane kubelet[783]: I0817 17:50:44.160327     783 dynamic_cafile_content.go:167] Starting client-ca-bundle::/etc/kubernetes/pki/ca.crt
Aug 17 17:50:49 external-control-plane kubelet[783]: W0817 17:50:49.173731     783 sysinfo.go:203] Nodes topology is not available, providing CPU topology
Aug 17 17:50:49 external-control-plane kubelet[783]: I0817 17:50:49.180202     783 container_manager_linux.go:278] "Container manager verified user specified cgroup-root exists" cgroupRoot=[kubelet]
Aug 17 17:50:49 external-control-plane kubelet[783]: I0817 17:50:49.180322     783 container_manager_linux.go:283] "Creating Container Manager object based on Node Config" nodeConfig={RuntimeCgroupsName: SystemCgroupsName: KubeletCgroupsName: ContainerRuntime:remote CgroupsPerQOS:true CgroupRoot:/kubelet CgroupDriver:cgroupfs KubeletRootDir:/var/lib/kubelet ProtectKernelDefaults:false NodeAllocatableConfig:{KubeReservedCgroupName: SystemReservedCgroupName: ReservedSystemCPUs: EnforceNodeAllocatable:map[pods:{}] KubeReserved:map[] SystemReserved:map[] HardEvictionThresholds:[]} QOSReserved:map[] ExperimentalCPUManagerPolicy:none ExperimentalTopologyManagerScope:container ExperimentalCPUManagerReconcilePeriod:10s ExperimentalMemoryManagerPolicy:None ExperimentalMemoryManagerReservedMemory:[] ExperimentalPodPidsLimit:-1 EnforceCPULimits:true CPUCFSQuotaPeriod:100ms ExperimentalTopologyManagerPolicy:none}
Aug 17 17:50:49 external-control-plane kubelet[783]: I0817 17:50:49.180363     783 topology_manager.go:120] "Creating topology manager with policy per scope" topologyPolicyName="none" topologyScopeName="container"
Aug 17 17:50:49 external-control-plane kubelet[783]: I0817 17:50:49.180386     783 container_manager_linux.go:314] "Initializing Topology Manager" policy="none" scope="container"
Aug 17 17:50:49 external-control-plane kubelet[783]: I0817 17:50:49.180405     783 container_manager_linux.go:319] "Creating device plugin manager" devicePluginEnabled=true
Aug 17 17:50:49 external-control-plane kubelet[783]: I0817 17:50:49.180549     783 remote_runtime.go:62] parsed scheme: ""
Aug 17 17:50:49 external-control-plane kubelet[783]: I0817 17:50:49.180571     783 remote_runtime.go:62] scheme "" not registered, fallback to default scheme
Aug 17 17:50:49 external-control-plane kubelet[783]: I0817 17:50:49.180605     783 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{/run/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}
Aug 17 17:50:49 external-control-plane kubelet[783]: I0817 17:50:49.180625     783 clientconn.go:948] ClientConn switching balancer to "pick_first"
Aug 17 17:50:49 external-control-plane kubelet[783]: I0817 17:50:49.180708     783 remote_image.go:50] parsed scheme: ""
Aug 17 17:50:49 external-control-plane kubelet[783]: I0817 17:50:49.180723     783 remote_image.go:50] scheme "" not registered, fallback to default scheme
Aug 17 17:50:49 external-control-plane kubelet[783]: I0817 17:50:49.180740     783 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{/run/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}
Aug 17 17:50:49 external-control-plane kubelet[783]: I0817 17:50:49.180756     783 clientconn.go:948] ClientConn switching balancer to "pick_first"
Aug 17 17:50:49 external-control-plane kubelet[783]: I0817 17:50:49.180824     783 kubelet.go:404] "Attempting to sync node with API server"
Aug 17 17:50:49 external-control-plane kubelet[783]: I0817 17:50:49.180856     783 kubelet.go:272] "Adding static pod path" path="/etc/kubernetes/manifests"
Aug 17 17:50:49 external-control-plane kubelet[783]: I0817 17:50:49.180895     783 kubelet.go:283] "Adding apiserver pod source"
Aug 17 17:50:49 external-control-plane kubelet[783]: I0817 17:50:49.180921     783 apiserver.go:42] "Waiting for node sync before watching apiserver pods"
Aug 17 17:50:49 external-control-plane kubelet[783]: I0817 17:50:49.183415     783 kuberuntime_manager.go:222] "Container runtime initialized" containerRuntime="containerd" version="v1.5.1" apiVersion="v1alpha2"
Aug 17 17:50:50 external-control-plane kubelet[783]: I0817 17:50:50.183844     783 apiserver.go:52] "Watching apiserver"
Aug 17 17:50:53 external-control-plane kubelet[783]: E0817 17:50:53.485571     783 aws_credentials.go:77] while getting AWS credentials NoCredentialProviders: no valid providers in chain. Deprecated.
Aug 17 17:50:53 external-control-plane kubelet[783]:         For verbose messaging see aws.Config.CredentialsChainVerboseErrors
Aug 17 17:50:53 external-control-plane kubelet[783]: I0817 17:50:53.486844     783 server.go:1190] "Started kubelet"
Aug 17 17:50:53 external-control-plane kubelet[783]: I0817 17:50:53.488342     783 server.go:149] "Starting to listen" address="0.0.0.0" port=10250
Aug 17 17:50:53 external-control-plane kubelet[783]: I0817 17:50:53.491125     783 server.go:405] "Adding debug handlers to kubelet server"
Aug 17 17:50:53 external-control-plane kubelet[783]: I0817 17:50:53.492068     783 fs_resource_analyzer.go:67] "Starting FS ResourceAnalyzer"
Aug 17 17:50:53 external-control-plane kubelet[783]: I0817 17:50:53.498226     783 volume_manager.go:271] "Starting Kubelet Volume Manager"
Aug 17 17:50:53 external-control-plane kubelet[783]: I0817 17:50:53.498917     783 desired_state_of_world_populator.go:141] "Desired state populator starts to run"
Aug 17 17:50:53 external-control-plane kubelet[783]: E0817 17:50:53.505156     783 kubelet.go:2211] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized"
Aug 17 17:50:53 external-control-plane kubelet[783]: I0817 17:50:53.505430     783 client.go:86] parsed scheme: "unix"
Aug 17 17:50:53 external-control-plane kubelet[783]: I0817 17:50:53.505448     783 client.go:86] scheme "unix" not registered, fallback to default scheme
Aug 17 17:50:53 external-control-plane kubelet[783]: I0817 17:50:53.505511     783 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}
Aug 17 17:50:53 external-control-plane kubelet[783]: I0817 17:50:53.505534     783 clientconn.go:948] ClientConn switching balancer to "pick_first"
Aug 17 17:50:53 external-control-plane kubelet[783]: I0817 17:50:53.600711     783 kubelet_node_status.go:71] "Attempting to register node" node="external-control-plane"
Aug 17 17:50:53 external-control-plane kubelet[783]: I0817 17:50:53.615367     783 kubelet_node_status.go:109] "Node was previously registered" node="external-control-plane"
Aug 17 17:50:53 external-control-plane kubelet[783]: I0817 17:50:53.615477     783 kubelet_node_status.go:74] "Successfully registered node" node="external-control-plane"
Aug 17 17:50:53 external-control-plane kubelet[783]: I0817 17:50:53.683944     783 kubelet_network_linux.go:56] "Initialized protocol iptables rules." protocol=IPv4
Aug 17 17:50:53 external-control-plane kubelet[783]: I0817 17:50:53.728754     783 cpu_manager.go:199] "Starting CPU manager" policy="none"
Aug 17 17:50:53 external-control-plane kubelet[783]: I0817 17:50:53.728803     783 cpu_manager.go:200] "Reconciling" reconcilePeriod="10s"
Aug 17 17:50:53 external-control-plane kubelet[783]: I0817 17:50:53.728829     783 state_mem.go:36] "Initialized new in-memory state store"
Aug 17 17:50:53 external-control-plane kubelet[783]: I0817 17:50:53.729103     783 state_mem.go:88] "Updated default CPUSet" cpuSet=""
Aug 17 17:50:53 external-control-plane kubelet[783]: I0817 17:50:53.729144     783 state_mem.go:96] "Updated CPUSet assignments" assignments=map[]
Aug 17 17:50:53 external-control-plane kubelet[783]: I0817 17:50:53.729165     783 policy_none.go:44] "None policy: Start"
Aug 17 17:50:53 external-control-plane kubelet[783]: I0817 17:50:53.730424     783 manager.go:600] "Failed to retrieve checkpoint" checkpoint="kubelet_internal_checkpoint" err="checkpoint is not found"
Aug 17 17:50:53 external-control-plane kubelet[783]: I0817 17:50:53.730713     783 plugin_manager.go:114] "Starting Kubelet Plugin Manager"
Aug 17 17:50:53 external-control-plane kubelet[783]: I0817 17:50:53.810912     783 kubelet_network_linux.go:56] "Initialized protocol iptables rules." protocol=IPv6
Aug 17 17:50:53 external-control-plane kubelet[783]: I0817 17:50:53.810961     783 status_manager.go:157] "Starting to sync pod status with apiserver"
Aug 17 17:50:53 external-control-plane kubelet[783]: I0817 17:50:53.810994     783 kubelet.go:1846] "Starting kubelet main sync loop"
Aug 17 17:50:53 external-control-plane kubelet[783]: E0817 17:50:53.811085     783 kubelet.go:1870] "Skipping pod synchronization" err="PLEG is not healthy: pleg has yet to be successful"
Aug 17 17:50:53 external-control-plane kubelet[783]: I0817 17:50:53.911335     783 topology_manager.go:187] "Topology Admit Handler"
Aug 17 17:50:53 external-control-plane kubelet[783]: I0817 17:50:53.911496     783 topology_manager.go:187] "Topology Admit Handler"
Aug 17 17:50:53 external-control-plane kubelet[783]: I0817 17:50:53.911545     783 topology_manager.go:187] "Topology Admit Handler"
Aug 17 17:50:53 external-control-plane kubelet[783]: I0817 17:50:53.911612     783 topology_manager.go:187] "Topology Admit Handler"
Aug 17 17:50:54 external-control-plane kubelet[783]: I0817 17:50:54.005197     783 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"k8s-certs\" (UniqueName: \"kubernetes.io/host-path/62d94253dfb3bc7efea906594d5c451f-k8s-certs\") pod \"kube-controller-manager-external-control-plane\" (UID: \"62d94253dfb3bc7efea906594d5c451f\") "
Aug 17 17:50:54 external-control-plane kubelet[783]: I0817 17:50:54.005341     783 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"usr-local-share-ca-certificates\" (UniqueName: \"kubernetes.io/host-path/62d94253dfb3bc7efea906594d5c451f-usr-local-share-ca-certificates\") pod \"kube-controller-manager-external-control-plane\" (UID: \"62d94253dfb3bc7efea906594d5c451f\") "
Aug 17 17:50:54 external-control-plane kubelet[783]: I0817 17:50:54.005413     783 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"ca-certs\" (UniqueName: \"kubernetes.io/host-path/949099c6581d332a8f1dbcdbd524d0ae-ca-certs\") pod \"kube-apiserver-external-control-plane\" (UID: \"949099c6581d332a8f1dbcdbd524d0ae\") "
Aug 17 17:50:54 external-control-plane kubelet[783]: I0817 17:50:54.005608     783 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"etc-ca-certificates\" (UniqueName: \"kubernetes.io/host-path/949099c6581d332a8f1dbcdbd524d0ae-etc-ca-certificates\") pod \"kube-apiserver-external-control-plane\" (UID: \"949099c6581d332a8f1dbcdbd524d0ae\") "
Aug 17 17:50:54 external-control-plane kubelet[783]: I0817 17:50:54.005654     783 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"ca-certs\" (UniqueName: \"kubernetes.io/host-path/62d94253dfb3bc7efea906594d5c451f-ca-certs\") pod \"kube-controller-manager-external-control-plane\" (UID: \"62d94253dfb3bc7efea906594d5c451f\") "
Aug 17 17:50:54 external-control-plane kubelet[783]: I0817 17:50:54.005690     783 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"etc-ca-certificates\" (UniqueName: \"kubernetes.io/host-path/62d94253dfb3bc7efea906594d5c451f-etc-ca-certificates\") pod \"kube-controller-manager-external-control-plane\" (UID: \"62d94253dfb3bc7efea906594d5c451f\") "
Aug 17 17:50:54 external-control-plane kubelet[783]: I0817 17:50:54.005740     783 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"k8s-certs\" (UniqueName: \"kubernetes.io/host-path/949099c6581d332a8f1dbcdbd524d0ae-k8s-certs\") pod \"kube-apiserver-external-control-plane\" (UID: \"949099c6581d332a8f1dbcdbd524d0ae\") "
Aug 17 17:50:54 external-control-plane kubelet[783]: I0817 17:50:54.005799     783 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"usr-local-share-ca-certificates\" (UniqueName: \"kubernetes.io/host-path/949099c6581d332a8f1dbcdbd524d0ae-usr-local-share-ca-certificates\") pod \"kube-apiserver-external-control-plane\" (UID: \"949099c6581d332a8f1dbcdbd524d0ae\") "
Aug 17 17:50:54 external-control-plane kubelet[783]: I0817 17:50:54.005935     783 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"flexvolume-dir\" (UniqueName: \"kubernetes.io/host-path/62d94253dfb3bc7efea906594d5c451f-flexvolume-dir\") pod \"kube-controller-manager-external-control-plane\" (UID: \"62d94253dfb3bc7efea906594d5c451f\") "
Aug 17 17:50:54 external-control-plane kubelet[783]: I0817 17:50:54.005980     783 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"kubeconfig\" (UniqueName: \"kubernetes.io/host-path/62d94253dfb3bc7efea906594d5c451f-kubeconfig\") pod \"kube-controller-manager-external-control-plane\" (UID: \"62d94253dfb3bc7efea906594d5c451f\") "
Aug 17 17:50:54 external-control-plane kubelet[783]: I0817 17:50:54.006075     783 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"etcd-certs\" (UniqueName: \"kubernetes.io/host-path/ce54e720217c6f6d55666abfec72a7cc-etcd-certs\") pod \"etcd-external-control-plane\" (UID: \"ce54e720217c6f6d55666abfec72a7cc\") "
Aug 17 17:50:54 external-control-plane kubelet[783]: I0817 17:50:54.006138     783 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"usr-share-ca-certificates\" (UniqueName: \"kubernetes.io/host-path/949099c6581d332a8f1dbcdbd524d0ae-usr-share-ca-certificates\") pod \"kube-apiserver-external-control-plane\" (UID: \"949099c6581d332a8f1dbcdbd524d0ae\") "
Aug 17 17:50:54 external-control-plane kubelet[783]: I0817 17:50:54.006180     783 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"usr-share-ca-certificates\" (UniqueName: \"kubernetes.io/host-path/62d94253dfb3bc7efea906594d5c451f-usr-share-ca-certificates\") pod \"kube-controller-manager-external-control-plane\" (UID: \"62d94253dfb3bc7efea906594d5c451f\") "
Aug 17 17:50:54 external-control-plane kubelet[783]: I0817 17:50:54.006296     783 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"etcd-data\" (UniqueName: \"kubernetes.io/host-path/ce54e720217c6f6d55666abfec72a7cc-etcd-data\") pod \"etcd-external-control-plane\" (UID: \"ce54e720217c6f6d55666abfec72a7cc\") "
Aug 17 17:50:54 external-control-plane kubelet[783]: I0817 17:50:54.006368     783 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"kubeconfig\" (UniqueName: \"kubernetes.io/host-path/2684a87c49138cdc77a25350f55b72ff-kubeconfig\") pod \"kube-scheduler-external-control-plane\" (UID: \"2684a87c49138cdc77a25350f55b72ff\") "
Aug 17 17:50:54 external-control-plane kubelet[783]: I0817 17:50:54.006474     783 reconciler.go:157] "Reconciler: start to sync state"
Aug 17 17:50:58 external-control-plane kubelet[783]: I0817 17:50:58.433331     783 kuberuntime_manager.go:1044] "Updating runtime config through cri with podcidr" CIDR="10.10.0.0/24"
Aug 17 17:50:58 external-control-plane kubelet[783]: I0817 17:50:58.434346     783 kubelet_network.go:76] "Updating Pod CIDR" originalPodCIDR="" newPodCIDR="10.10.0.0/24"
Aug 17 17:50:58 external-control-plane kubelet[783]: E0817 17:50:58.435169     783 kubelet.go:2211] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized"
Aug 17 17:50:58 external-control-plane kubelet[783]: I0817 17:50:58.519660     783 topology_manager.go:187] "Topology Admit Handler"
Aug 17 17:50:58 external-control-plane kubelet[783]: I0817 17:50:58.523653     783 topology_manager.go:187] "Topology Admit Handler"
Aug 17 17:50:58 external-control-plane kubelet[783]: W0817 17:50:58.534623     783 container.go:586] Failed to update stats for container "/kubelet/kubepods/besteffort/pod4bc152ed-542d-4e57-8d03-298c23f1d0fe": /sys/fs/cgroup/cpuset/kubelet/kubepods/besteffort/pod4bc152ed-542d-4e57-8d03-298c23f1d0fe/cpuset.mems found to be empty, continuing to push stats
Aug 17 17:50:58 external-control-plane kubelet[783]: I0817 17:50:58.553399     783 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"kube-api-access-mstxw\" (UniqueName: \"kubernetes.io/projected/4bc152ed-542d-4e57-8d03-298c23f1d0fe-kube-api-access-mstxw\") pod \"kube-proxy-ssq26\" (UID: \"4bc152ed-542d-4e57-8d03-298c23f1d0fe\") "
Aug 17 17:50:58 external-control-plane kubelet[783]: I0817 17:50:58.553664     783 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"kube-api-access-snl6d\" (UniqueName: \"kubernetes.io/projected/b8130e68-85a0-4a6a-940f-b066d4405b70-kube-api-access-snl6d\") pod \"kindnet-ml8zk\" (UID: \"b8130e68-85a0-4a6a-940f-b066d4405b70\") "
Aug 17 17:50:58 external-control-plane kubelet[783]: I0817 17:50:58.553984     783 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"lib-modules\" (UniqueName: \"kubernetes.io/host-path/4bc152ed-542d-4e57-8d03-298c23f1d0fe-lib-modules\") pod \"kube-proxy-ssq26\" (UID: \"4bc152ed-542d-4e57-8d03-298c23f1d0fe\") "
Aug 17 17:50:58 external-control-plane kubelet[783]: I0817 17:50:58.554188     783 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"cni-cfg\" (UniqueName: \"kubernetes.io/host-path/b8130e68-85a0-4a6a-940f-b066d4405b70-cni-cfg\") pod \"kindnet-ml8zk\" (UID: \"b8130e68-85a0-4a6a-940f-b066d4405b70\") "
Aug 17 17:50:58 external-control-plane kubelet[783]: I0817 17:50:58.554392     783 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"xtables-lock\" (UniqueName: \"kubernetes.io/host-path/b8130e68-85a0-4a6a-940f-b066d4405b70-xtables-lock\") pod \"kindnet-ml8zk\" (UID: \"b8130e68-85a0-4a6a-940f-b066d4405b70\") "
Aug 17 17:50:58 external-control-plane kubelet[783]: I0817 17:50:58.554537     783 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"lib-modules\" (UniqueName: \"kubernetes.io/host-path/b8130e68-85a0-4a6a-940f-b066d4405b70-lib-modules\") pod \"kindnet-ml8zk\" (UID: \"b8130e68-85a0-4a6a-940f-b066d4405b70\") "
Aug 17 17:50:58 external-control-plane kubelet[783]: I0817 17:50:58.554698     783 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"kube-proxy\" (UniqueName: \"kubernetes.io/configmap/4bc152ed-542d-4e57-8d03-298c23f1d0fe-kube-proxy\") pod \"kube-proxy-ssq26\" (UID: \"4bc152ed-542d-4e57-8d03-298c23f1d0fe\") "
Aug 17 17:50:58 external-control-plane kubelet[783]: I0817 17:50:58.554848     783 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"xtables-lock\" (UniqueName: \"kubernetes.io/host-path/4bc152ed-542d-4e57-8d03-298c23f1d0fe-xtables-lock\") pod \"kube-proxy-ssq26\" (UID: \"4bc152ed-542d-4e57-8d03-298c23f1d0fe\") "
Aug 17 17:50:58 external-control-plane kubelet[783]: E0817 17:50:58.732175     783 kubelet.go:2211] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized"
Aug 17 17:51:03 external-control-plane kubelet[783]: E0817 17:51:03.733925     783 kubelet.go:2211] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized"
Aug 17 17:51:04 external-control-plane kubelet[783]: E0817 17:51:04.100812     783 cadvisor_stats_provider.go:415] "Partial failure issuing cadvisor.ContainerInfoV2" err="partial failures: [\"/kubelet/kubepods/besteffort/pod4bc152ed-542d-4e57-8d03-298c23f1d0fe\": RecentStats: unable to find data in memory cache]"
Aug 17 17:51:14 external-control-plane kubelet[783]: E0817 17:51:14.133335     783 cadvisor_stats_provider.go:415] "Partial failure issuing cadvisor.ContainerInfoV2" err="partial failures: [\"/kubelet/kubepods/besteffort/pod4bc152ed-542d-4e57-8d03-298c23f1d0fe\": RecentStats: unable to find data in memory cache]"
Aug 17 17:51:15 external-control-plane kubelet[783]: I0817 17:51:15.105548     783 topology_manager.go:187] "Topology Admit Handler"
Aug 17 17:51:15 external-control-plane kubelet[783]: W0817 17:51:15.123892     783 container.go:586] Failed to update stats for container "/kubelet/kubepods/besteffort/podfd7fc818-7e9e-4b4c-9c4b-24d1e74460d1": /sys/fs/cgroup/cpuset/kubelet/kubepods/besteffort/podfd7fc818-7e9e-4b4c-9c4b-24d1e74460d1/cpuset.mems found to be empty, continuing to push stats
Aug 17 17:51:15 external-control-plane kubelet[783]: I0817 17:51:15.280911     783 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"kube-api-access-v7s8h\" (UniqueName: \"kubernetes.io/projected/fd7fc818-7e9e-4b4c-9c4b-24d1e74460d1-kube-api-access-v7s8h\") pod \"metrics-server-99b5b5fc6-8gfx4\" (UID: \"fd7fc818-7e9e-4b4c-9c4b-24d1e74460d1\") "
Aug 17 17:51:15 external-control-plane kubelet[783]: I0817 17:51:15.281624     783 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"tmp-dir\" (UniqueName: \"kubernetes.io/empty-dir/fd7fc818-7e9e-4b4c-9c4b-24d1e74460d1-tmp-dir\") pod \"metrics-server-99b5b5fc6-8gfx4\" (UID: \"fd7fc818-7e9e-4b4c-9c4b-24d1e74460d1\") "
Aug 17 17:51:17 external-control-plane kubelet[783]: I0817 17:51:17.788727     783 topology_manager.go:187] "Topology Admit Handler"
Aug 17 17:51:17 external-control-plane kubelet[783]: I0817 17:51:17.798481     783 topology_manager.go:187] "Topology Admit Handler"
Aug 17 17:51:17 external-control-plane kubelet[783]: W0817 17:51:17.803424     783 container.go:586] Failed to update stats for container "/kubelet/kubepods/besteffort/pod665442b7-2898-48d0-9d40-40a63827a0a6": /sys/fs/cgroup/cpuset/kubelet/kubepods/besteffort/pod665442b7-2898-48d0-9d40-40a63827a0a6/cpuset.mems found to be empty, continuing to push stats
Aug 17 17:51:17 external-control-plane kubelet[783]: I0817 17:51:17.810049     783 topology_manager.go:187] "Topology Admit Handler"
Aug 17 17:51:17 external-control-plane kubelet[783]: W0817 17:51:17.813424     783 container.go:586] Failed to update stats for container "/kubelet/kubepods/burstable/pod69eebc38-1eb9-4f31-9dbc-d920f7fc0325": /sys/fs/cgroup/cpuset/kubelet/kubepods/burstable/pod69eebc38-1eb9-4f31-9dbc-d920f7fc0325/cpuset.mems found to be empty, continuing to push stats
Aug 17 17:51:17 external-control-plane kubelet[783]: I0817 17:51:17.905031     783 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"config-volume\" (UniqueName: \"kubernetes.io/configmap/665442b7-2898-48d0-9d40-40a63827a0a6-config-volume\") pod \"local-path-provisioner-547f784dff-2zctb\" (UID: \"665442b7-2898-48d0-9d40-40a63827a0a6\") "
Aug 17 17:51:17 external-control-plane kubelet[783]: I0817 17:51:17.905122     783 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"config-volume\" (UniqueName: \"kubernetes.io/configmap/00911d7b-9402-4447-aae1-5e7e0cdc4e5b-config-volume\") pod \"coredns-558bd4d5db-vz9mc\" (UID: \"00911d7b-9402-4447-aae1-5e7e0cdc4e5b\") "
Aug 17 17:51:17 external-control-plane kubelet[783]: I0817 17:51:17.905182     783 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"kube-api-access-qg25p\" (UniqueName: \"kubernetes.io/projected/00911d7b-9402-4447-aae1-5e7e0cdc4e5b-kube-api-access-qg25p\") pod \"coredns-558bd4d5db-vz9mc\" (UID: \"00911d7b-9402-4447-aae1-5e7e0cdc4e5b\") "
Aug 17 17:51:17 external-control-plane kubelet[783]: I0817 17:51:17.905242     783 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"kube-api-access-wjmz7\" (UniqueName: \"kubernetes.io/projected/665442b7-2898-48d0-9d40-40a63827a0a6-kube-api-access-wjmz7\") pod \"local-path-provisioner-547f784dff-2zctb\" (UID: \"665442b7-2898-48d0-9d40-40a63827a0a6\") "
Aug 17 17:51:17 external-control-plane kubelet[783]: I0817 17:51:17.905294     783 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"config-volume\" (UniqueName: \"kubernetes.io/configmap/69eebc38-1eb9-4f31-9dbc-d920f7fc0325-config-volume\") pod \"coredns-558bd4d5db-xn6sq\" (UID: \"69eebc38-1eb9-4f31-9dbc-d920f7fc0325\") "
Aug 17 17:51:17 external-control-plane kubelet[783]: I0817 17:51:17.905346     783 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"kube-api-access-5sb2c\" (UniqueName: \"kubernetes.io/projected/69eebc38-1eb9-4f31-9dbc-d920f7fc0325-kube-api-access-5sb2c\") pod \"coredns-558bd4d5db-xn6sq\" (UID: \"69eebc38-1eb9-4f31-9dbc-d920f7fc0325\") "
Aug 17 17:51:22 external-control-plane kubelet[783]: I0817 17:51:22.495901     783 topology_manager.go:187] "Topology Admit Handler"
Aug 17 17:51:22 external-control-plane kubelet[783]: I0817 17:51:22.527463     783 topology_manager.go:187] "Topology Admit Handler"
Aug 17 17:51:22 external-control-plane kubelet[783]: I0817 17:51:22.657262     783 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"kube-api-access-vlv77\" (UniqueName: \"kubernetes.io/projected/3737bf83-8aa7-4c90-89b1-7165b6eb9c53-kube-api-access-vlv77\") pod \"controller-fb659dc8-4c9fv\" (UID: \"3737bf83-8aa7-4c90-89b1-7165b6eb9c53\") "
Aug 17 17:51:22 external-control-plane kubelet[783]: I0817 17:51:22.657362     783 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"kube-api-access-72lwx\" (UniqueName: \"kubernetes.io/projected/76be2662-178e-4033-8567-a2838d694e9d-kube-api-access-72lwx\") pod \"speaker-4jpjs\" (UID: \"76be2662-178e-4033-8567-a2838d694e9d\") "
Aug 17 17:51:23 external-control-plane kubelet[783]: E0817 17:51:23.714126     783 cadvisor_stats_provider.go:415] "Partial failure issuing cadvisor.ContainerInfoV2" err="partial failures: [\"/kubelet/kubepods/besteffort/pod665442b7-2898-48d0-9d40-40a63827a0a6\": RecentStats: unable to find data in memory cache], [\"/kubelet/kubepods/burstable/pod69eebc38-1eb9-4f31-9dbc-d920f7fc0325\": RecentStats: unable to find data in memory cache], [\"/kubelet/kubepods/besteffort/podfd7fc818-7e9e-4b4c-9c4b-24d1e74460d1\": RecentStats: unable to find data in memory cache]"
Aug 17 17:51:24 external-control-plane kubelet[783]: E0817 17:51:24.217714     783 cadvisor_stats_provider.go:415] "Partial failure issuing cadvisor.ContainerInfoV2" err="partial failures: [\"/kubelet/kubepods/besteffort/podfd7fc818-7e9e-4b4c-9c4b-24d1e74460d1\": RecentStats: unable to find data in memory cache], [\"/kubelet/kubepods/burstable/pod69eebc38-1eb9-4f31-9dbc-d920f7fc0325\": RecentStats: unable to find data in memory cache], [\"/kubelet/kubepods/besteffort/pod665442b7-2898-48d0-9d40-40a63827a0a6\": RecentStats: unable to find data in memory cache]"
